### ISSUE TITLE
the special characters are interpreted in a different manner

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#259]
Version: 1.9-current
Original reporter: 

In HTML, the text is as below -
Â·     updates,
 

Â·     supplements,

 

Â·     Internet-based services, and

 

Â·     support services

The above text IS DEPICTED as shown in the below error displayed in the converted | generated PDF form the above html -

ÃÂ·Ã Ã Ã Ã updates,

ÃÂ·Ã Ã Ã Ã supplements,

ÃÂ·Ã Ã Ã Ã Internet-based services, and

ÃÂ·Ã Ã Ã Ã support services

-----
is it possible to give us the appropriate solutions.

Thank You,
regards
Kiran Jayadeva

**Comment by jaysb29** [comment]
I was able to generate it properly in my pdf file
[outfile_5.pdf](https://github.com/michaelrsweet/htmldoc/files/847673/outfile_5.pdf)
