### ISSUE TITLE
<img> using src="data:image/png;base64,...." not rendering in PDF

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#292]
Version: -feature
Original reporter: Mark Fisher

<img> tags like the following do not render in the resulting PDF

<img id="signature-pad-data-admin" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAmAAAAB2CAYAAABvey9/AAAVBklEQVR4Ae2dC7BVVRnHU96IjxLRUAEfaD5IK5XyEZovxEcP0xp1GrUwdZpKUscxUywflaZOOTSmY2NOWo5kDYpoqUmi5AtRIRHjEaI8BB8oCij1/9dZtNzue7nn3rPPfpzfN/OftfY65+z1fb+9YK279tprf+hDGAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAARPYAAy5ETD7E2q136L037l5QsUQgAAEIAABCDSVAAOwpuJ+X2Un6ejmWsl0peOkNdISaXNpjvSG9LL0urRawiAAAQhAAAIQqACB7hWIoQoh7KEgrmsnkHf12SppqeQBmtPl0rJa3mWxFuv4LQkrLoEN5dr+0ihpE2mWNE2aLGEQgAAEIFBxAsyA5XeBzf5E6SfSwAzceFPnXFSTB2QvSQtrqWfVXqwdr1CKNZdAX1U3XhqZUu05KrsypZwiCEAAAhCoEAEGYPlfzP5y4SFp55xc8UDNg7EFUhiYhcGZjz1w80DuPQnrOgFf74eloW2cyrehPSP2ThufUwwBCEAAAhUgwACsGBdxI7nxqLRrMdz5gBdrVbJECoOxMLPm1LNr4Tjc+vQtU+z/BHZT9lTpCMkDr+5SW8YArC0ylEMAAhCoEAEGYMW5mN3kyiHSNtIgyeuBtpA8Y7KxtGVNPv6wNEDaTCqaeebGDw14sOYZtNdq8q3OuZIHc69KXqPmwYbXtgX5QQOXebbNT4W6fYY26kFLT8lrp5z2lswsyJ/7Myv8zufx+Xzsz+2Xz+sBr8vtiz9zmeVjywPI+HMf+3s9IvVS3j4E9VM+XC/H4eu0tTRM2krqiNmHMdI1Hfky34EABCAAgfIScKeClZeABwQeiLnjd5pUGLQ59YDAg4VWNg9witbm/aTrbdL90r2SH6zAIAABCECg4gSK1hlVHHfu4XltkQdjHrB5q4swePNMmo8tf2dTyWXOe7YozDYpW2or2gBskmiOkuwXVg4CB8nNYyQPlOdL/jcyU/JA+hnJM6e+nmFm1rOnnlXFIAABCLyPAAOw9+HgoA0Cvq3nQVhfqU9N4dabU98S9GycOx3fmvN3fMvPHY8/8y1Ul/tWowd9/tzlvm1n+Rz+3GX+XXw70Z1ZuDXpzmxlTS7zbUzLZW9Lvv3pOuLU5b4V6Rh8O9Tnsz8uc/t3Xclbi8EP+xVicVko9++CHKMVzuU4Fkk+v295eu3cJ6XvSbEt1MHukn3Cik/g63LxW9Ke7bjqtuW2EAZgbhM+Xi65na2Q3B5CW3U7ddt1G/YAzu3F7cHt5yXpxVrq72MQgEDFCPg/CAwCEMiOwME69V2SB2axeebr7riAfCEJ+P/I+6SDcvLOA3kP2ubWNFvpLGmB9LDkwR4GAQhAAAIQgEBE4Ejlwy0pd5RBV0ffIVtcAh58PSKF61a0dLF8+7K0i/QpyYP9Q6VjJT8AgkEAAhCAAARaikA3RXuZ5NmLZKd9q8r8OVZ8AiPkYvL6tXfs240ecPuW4nxphvSMNFfy7cb2fpvFZzeqTg8iMQhAoIAEvC4BgwAEGkdgG53qFumAlFNeo7IxkjtbrPgE9ktxcY7KRkter7WFtIM0U/Iarqclr1Ns6/r6SeQhktuINSjKb6u8Z628HrFRdopONETyQwNvShgEIAABCECgkgSOVlRer5OczViqshMrGXG1g/payrV0WVbmB0W2kvaWfGvxbOkX0gTpWcmDqGTb6sjxdP3OAz4MAhCAAAQgUCkCflry51LaLcdHVe5ZEqx8BE6Vy8kBjsvytC1V+emSb20mfWvveLa+P1DCIAABCEAAApUg4G0J2uoMr9NnfSsRZWsGcb7CTg5qXFYE89qu4ZJnyb4rnSV5du4oyesMk377+DnJM2wYBCAAAQhAoLQEvJDenfFqKdnZ+VbRCRJWbgJnyP3ktT2sJCFdmuK7Y/Erzry5MgYBCEAAAhAoHYFh8vgxKdk5+9jl3HIUhArYOMWQvMY7liQuz5Cl+e94pko9SxIHbkIAAhCAAAT+u5nqxeKQNuvl9V+XS3Rs1WkodyiU5ADsXpV9piQhehA2PiUGx+TbkdweFwQMAhCAAASKTWCE3HOnleyQffyCtL+EVYuAbyOnXW+XeWBTBuslJz1oTItjgcr9OQYBCEAAAhAoHIHN5dGNUloHtlblfvqRmQRBqKj5dVFp195l95UkZs/KTm4jDu9d5u0vMAhAAAIQgEBhCHjvriVSWgfsfZn2LYynOJIVAQ+uH5DS2oDLTpbKYN7gta0Z3JFlCAAfIQABCECg+gS8aeVEKa3T9ROO50m8RUIQWsS8lspbPMyVkm1ikcrKMoPkweSylBi8dhGDAAQgAAEI5ErgFNXu18wkO1ofe93PIAlrTQIedKc9/XpwiXB4v7Bk2/52ifzHVQhAAAIQqBgBv9cv7ak3d1azpEMrFi/hdI7AUP0sOYB5tHOnyuVX/gMj6b83DMYgAAEIQAACTSfgGYyFUrJjWqmy8yWeFBMEbB2BJ5RLthXflvatyqKbb0N6/WLsvwdlGAQgAAEIQKBpBLx25xLJTzPGHZLzfvptOwmDQJLA0SpItpfQZsoyCPOgyzNfTsvgs9zEIAABCECgCgS8vcRfpWRHulRl3v8Jg0B7BLz9SLLt+Pj+9n7EZxCAAAQgAIFWJuCdzD3QSnagv1dZ/1YGQ+wdJtBN35wgJduQj38g8UYEQcAgAAEIQAACJuBbLWdKfm1Q3HF6K4HjJAwC9RDw3lq/k+K2FPJemM8grB6afBcCEIAABCpJoJ+iSnvK8U6Ve98vDAKdJdDWBqfeOwyDAAQgAAEItCwBbx0wRQqzE07fkDwbxgJkQcC6ROAM/TpuWyG/WOW9u3RmfgwBCEAAAhAoKYHD5bdvMYZO0elsaZiEQaARBDyInybFbSzkeaCjEYQ5BwQgAAEIlIrAufI2ud7rlyrz7UgMAo0k4L3iXpbCwCuknh3DIAABCEAAAi1BwJ3hTVLoBJ2+K42WMAhkReAynThuc867DIMABCAAAQhUnsDGitB7McUd4Ss6/nTlIyfAvAkcIQfiduf8zXk7Rf0QgAAEIACBrAkMVAVPS3En+JSOecoxa/Kc3wS8N5gX3sftzzOvgyUMAhCAAAQgUEkC7uT+KcWd3yQdb1bJaAmqqASulWNxG3T+yqI6i18QgAAEIACBrhAYoh/Pk+KOz2vAPCOBQaCZBIaosjVS3BZXNNMB6oIABCAAAQg0g8BgVTJPiju8q3TsF21jEMiDwHhVGrdH5/fKwxHqhAAEIAABCGRBYFuddI4Ud3aXZlER54RAHQRG6btxm3T+2Dp+z1chAAEIQAAChSXgwdcLUtzRXVRYb3GslQgcn2iXbqMXtBIAYoUABNZPoPv6v8I3IFA4AlvLowekHSLPvq88ey5FQMjmRmCXlJp7pJRRBAEIQAACECgNgR3lafK243dK4z2OtgKB0xRkPDPrPJsAt8KVJ0YI1EGAGbA6YPHV3Al4ZuEeybcfbd5jyS/Uvt4HWGEJ+P8Zr4uyTZR83apsg1KCG5xSRhEEIAABCECg8AT8FNlrUphZWK38FwvvNQ568DVZCtfN+ar/4ecXcId4Q8pLuQUFgwAEIACBchEYKXdXSaEzW678fuUKoWW9PSa6buH6uazK5idxQ6whvaTKARMbBCBQPwH2SqqfGb9oLoExqs63rXrWqp2pdLg0pXZMUmwCO6a4l1aW8rXSFvVL8dzvKMUgAAEIrCPAAGwdCjIFI9BL/lwu/UzaoObb3UoPlGbXjkmKT+AfKS7OSCmrUpHfR5q0eckCjiEAAQhAAAJFI7CFHPqjFG7fOL1B6i1h5SKwq9yNr6PzLquyeW1iMmb/IYFBAAIQgAAECktgN3k2XQod2HvKn1RYb3FsfQT8RGC4liFNe0pwfecp0+dpg85xZQoAXyEAgewJVP1ppOwJUkMjCXirAr9Eu3/tpH7q0WWP1I5JykfAs5YeeIXbyM6/Xb4w6vK4b8q3qx5zSsgUQQACEIBA0Ql4LaJ3sl8rhVkSL7bfRsLKTeAguR+uaUg3LXdI6/X+7JSYh6/3V3wBAhCAAAQg0EQCm6iu26XQOTv1+i/WewlCBewbiiG+tp7VrLpNVoBxzDw0UvUrTnwQgAAESkZgqPz1TFforDwDNlbCqkPgdIUSrq/TBdUJLTWSLVXqnf7jmFn/lYqKQghAAAIQyIOAnxRbIYWOaqXy7Gyfx5XIts4jomvsa+1B9oBsq8z17Geq9tCmQ+p1jBgEIAABCEAgVwI9VPuVUuicnM6S/J5HrHoEPNiK1/b5eo+uXpjrInpSubhtL9Nxn3WfkoEABCAAAQjkQGCg6nxQijuoCTr+SA6+UGXzCDyrquJrPlXH4anI5nmRfU37J+J0zNdlXy01QAACEIAABNomcIg+WiSFjtizIudLVeyIFRYWEThO+XDdQ1rFWbA/pMQ5LOJAFgIQgAAEINA0At1U00WSN1QNne8S5Q+XsNYg4P0Gp0nh+jt1Gwj7vSlbevMt9DVSHKOf5sUgAAEIQAACTSewlWr8ixR3SlN0PKjpnlBh3gT2kgPJAYpnQKtikxRI3M79B8ceVQmOOCAAAQhAoDwEPidXX5ZCp+Rbjn4fXk8Ja00CVyjs0B6cviN5hrTsNlgBxDO8ju22sgeF/xCAAAQgUC4CXtN1oRTvhbRcx18oVxh4mwEBPw3o7UbiQdhXM6in2af8cyIm/7GxfbOdoD4IQAACEGhdApsr9HukuIP9u449Q4BBwAR+LcXtwwvXy2xj5Xwcj/NXlzkgfIcABCAAgXIR2Efu/kuKO6OrdOx9vzAIBAIepK+SQjtxvl/4sGTpkfLXs10hFqdLJe+Gj0EAAhCAAAQyJ3CaalgthY7I7/v7fOa1UkFZCdwsx0NbcXpyCQPZTD4vlOI4PBjjbQ4lvJi4DAEIQKBsBPzC7BukuBN6QsesfynblWyuv59NtJk5za2+IbUl273/DVzYkDNzEghAAAIQgEA7BLzFxMNSPPhyp8RTju1A46N1BGYoF7edL637pPiZXnIx+TDBHcV3Gw8hAAEIQKDsBPZWAAuk0IF6Hc/JEgaBjhI4T18M7cepH9Yoy1sRzkr47v3N/M5LDAIQgAAEIJAZga/ozPFf//N07E02MQjUQ8Dv/3xVigdhZXk7wmMJv39UT+B8FwIQgAAEIFAvgbH6QdxhPqhj34rEINAZAjfpR3F7+ltnTtLk3/gpTi+2j/3+WJN9oDoIQAACEGgRAt0U5y1S3OmM0/GGLRI/YWZD4ACdNm5Tzh+YTVUNO2vyxeJ+wTwGAQhAAAIQaDiBTXTGqVLoKL3D/ZkNr4UTtiqBWQo8tC2n3lW+yPaknIv9/VORncU3CEAAAhAoJ4Ehcnu+FDocbzJ5oIRBoFEEztGJQvty6tt7RV1T+NGaf7G/fpgAgwAEIAABCDSMwD460+tS6GyeVn6nhp2dE0HgfwS8hvAdKbQzp0V9PdGPE356sDhQwiAAAQhAAAINIXCSzuJbjaFTnKj8gIacmZNA4IMExqsotLWQFm1hu1+X5Dc8BP+c3iphEIAABCAAgS4T8D5MY6S4k/Fi+z5dPjMngEDbBEbqo7jNOX9921/P5ZMLUnw8OBdPqBQCEIAABCpFwDvY/0qKO8KLdcyTjpW6zIUMxgP/56W47fndokW5veetJ5Yl/HtKx/zbEAQMAhCAAAQ6T2Aj/fReKXSAvv3IS4U7z5Nf1k8gOfPqtnhF/afJ5Be/0VnDv42QHpVJTZwUAhCAAARahsA2itQL7EPHskL5fVsmegItCoFN5chbUmiHTr1TvsvzND/56Nm42K978nSIuiEAAQhAoPwEtlMIc6TQucxTvmiLn+US1iIErlGcoS2G9NycY7894dN7Ot4+Z5+oHgIQgAAESkxgsHyfL4WObqbyg0ocD66Xn4AHNquk0CadLpb8JoY87FBVGvvi/IV5OEKdEIAABCBQDQL9FcYsKXQu05X3QmMMAnkTSL7yym10dA5O9VKd8b8R+/GilPct0RxQUCUEIAABCDSCgJ/cul8Kg6/nlfeADINAEQjsKSfWSqF9Op2Tg2M/TPhgP07JwQ+qhAAEIACBihC4SnGEzm258kMrEhdhVIfARIUS2mhIj29ieB4Erkn4MEXH3i4DgwAEIAABCNRN4Bj9InRoTnmUvm6E/KAJBEaojridOv+41IwBkPfDm5ao309BDpMwCEAAAhCAQN0EBukXfpl26Nj8xBkGgaISeEiOhbYa0ma8I/K2lHrHFhUSfkEAAhCAQPEJ/FYuho5shvJ5PVlWfFJ4WAQCh8iJ0F7j9KcZObeLzjsppc6nVNYjozo5LQQgAAEItACByxSjOzKvbdm9BeIlxHIT8O3G+6R48OW8F+h/U2qUjdKJ7pK8v1eyLpd5PRgGAQhAAAIQ6DQBP/3oNWAf7/QZ+CEEmkvAg7AHpLSB0WGddOUT+t21knezf0lKnjs+zmq2TdViEIAABCAAAQhAoLgEusu1J6R4YOS8X1O0s9QR80DuSOlOKXmeto69Az4GAQhAAAIQgAAEWpbAYEW+TEoOlmarbMB6qAzX51NTfps8VzheoO/yIvr1QOVjCECg6wSa8Vh3173kDBCAQKsTOFYA0mal5ql8gvSctIPkF3r75fIemB0uHS115P+5V/S9S6TrpZUSBgEIQAACEIAABCAgAldLYaaqq6ln1Dxw86BrHwmDAAQgAAEIQAACEEgh4O0gvHi+s4MvPwF8g7SThEEAAhCAAAQgAAEIdJBAH33vEaneQZgHbt7rC4MABCAAAQhAAAIQ6ASB3vrN41JHBmHT9b0RnaiDn0AAAhDIlEBHFqdm6gAnhwAEINAJAr30Gy/M91OOtllSWITvQZcHaZ4pmyNhEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIBAWQn8Bzp2tLqy4/c7AAAAAElFTkSuQmCC">

**Comment by andersfylling** [comment]
Would love to see base64 support!

**Comment by michaelrsweet** [comment]
@andersfylling Data URI support was added in HTMLDOC 1.9.6.
