### ISSUE TITLE
Unable to print pdf with chinese characters

### ISSUE THREAD

**Issue by jaysb29** [michaelrsweet/htmldoc#299]
I have a html file which is in Chinese language. On converting to pdf it displays garbage characters instead of the chinies

**Comment by michaelrsweet** [comment]
Sorry, this is covered in the README. HTMLDOC does not support Unicode or Asian languages, nor do I have any plans to add support in the future as HTMLDOC is in maintenance mode.

The best HTMLDOC can do is some dynamic mapping of UTF-8 into a custom 8-bit character set (which happens automatically), but it lacks the fonts or ability to typeset Asian (or Arabic) text - the focus is really on "Western" languages that read left-to-right, and I never had the time, funding, or inspiration to further develop HTMLDOC for such things.
