### ISSUE TITLE
Support for curly/directional quotes

### ISSUE THREAD

**Issue by jaysb29** [michaelrsweet/htmldoc#300]
Do the pdf supports smart quotes ie curly quotes

**Comment by michaelrsweet** [comment]
It should with UTF-8 or the corresponding HTML entity (&foo;), however I haven't tried this. Holding as an issue for now, and am working on doing a 1.8.30 maintenance release.

**Comment by michaelrsweet** [comment]
(and might be something to automatically add as an option)

**Comment by michaelrsweet** [comment]
Verified that HTMLDOC 1.8.29 supports the standard HTML entity names as well as UTF-8 encoded values.
