### ISSUE TITLE
Fixing #273 causes an issue that does not allow placing horizontal line under the header

### ISSUE THREAD

**Issue by mdykierek** [michaelrsweet/htmldoc#303]
I guess fix for #273 does not allow to get the following effect now:
![image](https://cloud.githubusercontent.com/assets/27214784/24862971/4907dfd8-1dff-11e7-8219-afeceb912cc3.png)
and instead we are getting:
![image](https://cloud.githubusercontent.com/assets/27214784/24863004/69b90838-1dff-11e7-8e3c-26d66d54d8e0.png)
--browserwidth 850 \
--header tlc  \
--headfootfont Times-Italic  \
--headfootsize 11.0  \
The "underline" image 850x25px.

**Comment by michaelrsweet** [comment]
Will look at possible solutions...

**Comment by michaelrsweet** [comment]
OK, now limiting the height of these images to twice the header/footer text size - that will prevent the oversized logos (as was reported with Issue #273) while still allowing your usage to work.

[master aef3bdb] Fix header/footer scaling regression (Issue #303)
