### ISSUE TITLE
Microsoft Visual Studio won't build HTMDOC

### ISSUE THREAD

**Issue by mdykierek** [michaelrsweet/htmldoc#304]
Issues are:
- SLNs are from a newer version and VCPROJs older
- htmldoc.vcproj refers to non-existent files (for example sspi.c)

**Comment by michaelrsweet** [comment]
Will fix...

**Comment by michaelrsweet** [comment]
and checked in the vcxproj files and removed the old vcproj files... Still need to add the new source files for 1.9...

**Comment by michaelrsweet** [comment]
and these are now in master...
