### ISSUE TITLE
Document --hfimageN and $HFIMAGEn

### ISSUE THREAD

**Issue by hercross** [michaelrsweet/htmldoc#305]
Hi, my partner use this library for generate pdf file. And now I need to change footer text, and I don't now how to do...
I need add more lines, now I have one..

I have this:

`passthru("htmldoc --format pdf --left 2.5cm --right 1.5cm --top 2.0cm --bottom 0.5cm " .
                "--headfootsize 6 --textfont Arial --header '...' --footer '...' --linkcolor '#0000FF' " .
                "--size 'a4' --fontsize 9 --charset 8859-15 " .
                    "--webpage http://localhost/generarfacturapdf.php?idfactura=" . $_GET['idfactura'] . "&");`

And in the generarfacturapdf.php:

`echo "<!-- FOOTER CENTER \"Texto a mostrar" -->";`

How can I add one, two, three..... lines into the Footer?

Thanks a lot!!

**Comment by michaelrsweet** [comment]
HTMLDOC only supports single-line footers. Historically this has been simulated using header/footer images instead.

**Comment by hercross** [comment]
Ok.. so, I can put an image instead a text?? How can I do that?
Thanks

2017-04-19 14:53 GMT+02:00 Michael R Sweet <notifications@github.com>:

**Comment by michaelrsweet** [comment]
The --hfimage1 to --hfimage9 options specify header/footer images, which you can then reference in the page comments. See:

    https://michaelrsweet.github.io/htmldoc/htmldoc.html#4_3_1

Unfortunately, it appears that I haven't documented the --hfimageN command-line option, nor the page comments:

    --hfimageN filename

    (N = number from 1 to 10)

and then in the header/footer page comments you can use:

    $HFIMAGE1
    $HFIMAGE2
    $HFIMAGE3
    ...
    $HFIMAGE10

to include the corresponding image.

**Comment by hercross** [comment]
So, sorry i don't know enough php...

In my example..

In passthru("htmldoc --format pdf --left 2.5cm --right 1.5cm --top 2.0cm
--bottom 0.5cm " . "--headfootsize 6 --textfont Arial --header '...'
--footer '...' --linkcolor '#0000FF' " . "--size 'a4' --fontsize 9
--charset 8859-15 " . "--webpage
http://localhost/generarfacturapdf.php?idfactura=" . $_GET['idfactura'] .
"&");

I have put --hfimage1 imagename option?

Could be this way?

passthru("htmldoc --format pdf --left 2.5cm --right 1.5cm --top 2.0cm
--bottom 0.5cm " . "--headfootsize 6 --textfont Arial --header '...'
--footer '...' --linkcolor '#0000FF' " . "--size 'a4' --fontsize 9
--charset 8859-15 " . "--hfimage 'image.png'" . "--webpage
http://localhost/generarfacturapdf.php?idfactura=" . $_GET['idfactura'] .
"&");

And in my generarfacturapdf.php put $HFIMAGE1 in my footer section?

Thanks

2017-04-19 15:12 GMT+02:00 Michael R Sweet <notifications@github.com>:

**Comment by michaelrsweet** [comment]
Yes, exactly.

**Comment by hercross** [comment]
Ok, I'll try it..

Thanks..

2017-04-19 15:35 GMT+02:00 Michael R Sweet <notifications@github.com>:

**Comment by michaelrsweet** [comment]
[master 5583678] Add hfimage documentation (Issue #305)

**Comment by rajeshrajesh35** [comment]
Hey,

Could you please let me know how to add header/footer on each page?

Also, can we add link on header text?

**Comment by michaelrsweet** [comment]
@rajeshrajesh35 The HTMLDOC Users Guide explains how to add headers and footers. Note that the first page header is a separately configured thing for books (vs. web pages).

There is currently no way to add links on headers or footers.

**Comment by rajeshrajesh35** [comment]
@michaelrsweet Thanks for your response. can you please share the example how to add header and footer as i tried but i was not working
