### ISSUE TITLE
htmlsep.cxx error: ordered comparison between pointer and zero

### ISSUE THREAD

**Issue by tjelbert** [michaelrsweet/htmldoc#306]
building htmldoc-1.8.30 with 

llvm-4.0.0
gcc-7.1.0

Compiling htmlsep.cxx...
htmlsep.cxx:521:19: error: ordered comparison between pointer and zero ('int *' and 'int')
      if (heading >= 0)
          ~~~~~~~ ^  ~
1 error generated.

**Comment by michaelrsweet** [comment]
[master c6e3770] Fix pointer/integer comparison - missing dereference (Issue #306)
