### ISSUE TITLE
Windows installer issues

### ISSUE THREAD

**Issue by OlivierJHebert** [michaelrsweet/htmldoc#307]
Although I can launch the .msi document for the minecraft installer, I am not capable of launching the .msi installation program for your tool. I've included the file I could not launch if that helps. My laptop is running Windows 10.
[htmldoc-1.8.30-windows.zip](https://github.com/michaelrsweet/htmldoc/files/1069457/htmldoc-1.8.30-windows.zip)

**Comment by michaelrsweet** [comment]
The one difference might be that my MSI package is not signed, so perhaps Windows 10 doesn't like it? Do you get any errors in the event log?
