### ISSUE TITLE
table rows that are larger than page height are cut off

### ISSUE THREAD

**Issue by rseuhs** [michaelrsweet/htmldoc#308]
[table_row_cut_off.pdf](https://github.com/michaelrsweet/htmldoc/files/1072039/table_row_cut_off.pdf)

As can be seen in the example, a pdf-file that was created with htmldoc cuts off table rows that are taller than the page height.

I also tried to insert "`<!-- PAGE BREAK -->`" inside the tall `<td>`, but that did have no effect.

htmldoc version: 1.8.27

**Comment by rseuhs** [comment]
Retested with version 1.8.30 with the same results

**Comment by michaelrsweet** [comment]
OK, the PDF you attached was created by "WeasyPrint 0.26 (http://weasyprint.org/)", not HTMLDOC.

If this actually happens with HTMLDOC, please attach the HTML (you'll need to rename for Github) and I'll take a look...

**Comment by rseuhs** [comment]
That's embarassing, sorry, I have mixed that up. We were originally using htmldoc, but then changed to weasyprint because we could not get UTF8 to work. That was 2 years ago, so I forgot it :-/
