### ISSUE TITLE
Courier font is scaled down

### ISSUE THREAD

**Issue by mdykierek** [michaelrsweet/htmldoc#309]
Text within tt is rendered with Courier size 8.3 while the font size is set to 10: with --fontsize 10.0.
This did not occur prior to 1.9 release.

**Comment by michaelrsweet** [comment]
This was changed in v1.8.28, several years ago (2010 as far as I can see) in response to bugs that were reported. I don't recall the exact details but I think it had something to do with the Courier and Monospace fonts being larger than the variable-spaced fonts...

**Comment by mdykierek** [comment]
Not trying to argue, but now Monospace height is about x-height of Serif font for larger sizes.
Sorry for the attachment sizes, but they illustrate the typographical issue.
[uhtmldoc-1.8.27.pdf](https://github.com/michaelrsweet/htmldoc/files/1234501/uhtmldoc-1.8.27.pdf)
[htmldoc-1.9.pdf](https://github.com/michaelrsweet/htmldoc/files/1234503/htmldoc-1.9.pdf)

**Comment by michaelrsweet** [comment]
Will look at only doing the size adjustment just for Courier...

**Comment by mdykierek** [comment]
Mr. Sweet, the Courier New font is in general slightly smaller than Arial (Helvetica) and the problem PDFs from Aug 18, 2017 illustrate that it is even smaller after scaling. The "if" should probably have the opposite condition (t->typeface != TYPE_COURIER). I also took some time to compare Arial against DejaVu Sans Mono and the metrics for the same point size are pretty close, so please do consider the removal of font scaling. Currently <tt>code</tt> within an Arial text is hard-to-read-small.

**Comment by michaelrsweet** [comment]
Reconsidering

**Comment by Symbian9** [comment]
Any news on this font issue?

**Comment by michaelrsweet** [comment]
No, not yet. I'm not doing much work this summer so this won't be looked at until at least September.

**Comment by michaelrsweet** [comment]
[master dd7790a] Remove courier sizing hack (Issue #309)
