### ISSUE TITLE
anchor links which has a span text is not getting displayed

### ISSUE THREAD

**Issue by jaysb29** [michaelrsweet/htmldoc#311]
I am not able to install https://github.com/michaelrsweet/htmldoc/archive/release-1.8.27.zip. When we upgraded to the latest version 

    <h2><a name="test"><span class="mw-headline" id="Product_resources">Product resources</span></a></h2>

The problem is whenever we have a span in a a tag. it is not getting displayed

**Comment by michaelrsweet** [comment]
Hmm, strange. The text *does* show up in the footer (current heading). Investigating...

**Comment by michaelrsweet** [comment]
Looks like the issue is that SPAN is not a standard markup tag for HTMLDOC (since it was introduced in HTML 4.0 and HTMLDOC only implements 3.2 + a few 4.0 things), but I'm adding it in now...

**Comment by michaelrsweet** [comment]
[master 081d4de] Add support for SPAN element (Issue #311)
