### ISSUE TITLE
Support limited UTF-8 text (whatever can be stuffed in 8 bits) and strip (invalid) BOM chars

### ISSUE THREAD

**Issue by LeftWing** [michaelrsweet/htmldoc#314]
Whenever I create a PDF file from an HTML document, I get: these characters at the top of the PDF document: 

`ï»¿`

I tried changing the character set, and that does affect the strange characters, but they always remain. I've tried using your example HTML as well as something as simple as:

`<html><body>Test</body></html>`

but the characters are always there - it doesn't matter if I use the GUI or the command. The only time they aren't there is if I use the URL (like your site), then they don't appear in the PDF.

Do you know what I'm doing wrong?

[test2.pdf](https://github.com/michaelrsweet/htmldoc/files/1235244/test2.pdf)

**Comment by Jonowa** [comment]
These three characters marked the BOM of an UTF-8 file. Try to convert your HTML to UTF-8 without BOM.

**Comment by michaelrsweet** [comment]
Windows (incorrectly) includes the BOM in UTF-8 encoded files, but byte order marks are only value for UTF-16 encoded files.

I will consider adding code to strip the BOM (and maybe throw an obnoxious warning about it?) so you don't get these random characters in your output, but the fix should be to your HTML files...

**Comment by michaelrsweet** [comment]
Also, HTMLDOC doesn't actually support UTF-8 at this time...  So changing the title to reflect this and I'll see what I can do.

(There *was* some code in the original 1.9 branch to support ASCII + up to 128 Unicode chars from a UTF-8 source file - I'll try to revive that)

**Comment by michaelrsweet** [comment]
[master 09bc4b1] Add very limited Unicode/UTF-8 support (Issue #314)

**Comment by LeftWing** [comment]
Thank you, I'm looking forward to trying it out. Will this be available in a future release?

**Comment by michaelrsweet** [comment]
Yes, I'll do some more testing (particularly with the Markdown input support since I haven't validated that code path with these changes yet) but this will be part of the 1.9.1 update I'm planning on doing in the next couple weeks.

**Comment by LeftWing** [comment]
Great, once again - thank you very much!
