### ISSUE TITLE
Heavy tick (&#10004 ) not getting supported

### ISSUE THREAD

**Issue by jaysb29** [michaelrsweet/htmldoc#315]
&#10004  Is this tag supported. As when we are generating the pdf, we are getting this rendered as ?

**Comment by michaelrsweet** [comment]
None of the bundled fonts have this emoji, so you won't get anything beyond the ? substitution glyph.

**Comment by malmoore** [comment]
Do any of the bundled fonts have any sort of emoji that is similar to a check mark?

**Comment by michaelrsweet** [comment]
Doesn't look like it, sorry...
