### ISSUE TITLE
Compiling error 1.9.1

### ISSUE THREAD

**Issue by kleinadam** [michaelrsweet/htmldoc#318]
Can some help?  (Debian 8, 64bit)

make always stops on that error: 
... 
... 
png.c:3446:1: warning: ‘png_product2’ defined but not used [-Wunused-function]
 png_product2(png_fixed_point a, png_fixed_point b)
 ^
../Makedefs:85: recipe for target 'png.o' failed
make[1]: *** [png.o] Error 1
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by monark88** [comment]
Same issue

**Comment by michaelrsweet** [comment]
I cannot reproduce on my Ubuntu system...

What version of GCC are you using?

What options did you pass to the configure script?

**Comment by monark88** [comment]
gcc version 4.9.2 (Debian 4.9.2-10)

I did not pass any options to the configure script

**Comment by michaelrsweet** [comment]
Hmm, my Ubuntu is showing GCC 6.3.0-2ubuntu1...

Try installing the libpng-devel package and use the OS-supplied PNG library.

**Comment by monark88** [comment]
Could very well be GCC version.  I'm on managed server, so can't install PNG.. It will be ok, one day when this server gets upgraded.  I was able to get a .... far.... older version to compile.

**Comment by michaelrsweet** [comment]
Can you post the whole make log along with your Makedefs file? It shouldn't fail the build for that warning...

**Comment by monark88** [comment]
Sure, glad to help, and thankful for the help.

[build.log](https://github.com/michaelrsweet/htmldoc/files/1480133/build.log)
[Makedefs.txt](https://github.com/michaelrsweet/htmldoc/files/1480138/Makedefs.txt)

**Comment by kleinadam** [comment]
gcc (Debian 4.9.2-10) 4.9.2

Making all in jpeg...
Making all in png...
Compiling png.c...
../Makedefs:85: recipe for target 'png.o' failed
Makefile:31: recipe for target 'all' failed

[make.errors.warnings.txt](https://github.com/michaelrsweet/htmldoc/files/1484743/make.errors.warnings.txt)
[Makedefs.txt](https://github.com/michaelrsweet/htmldoc/files/1484744/Makedefs.txt)

**Comment by kleinadam** [comment]
Ok, it works after installing "libpng12-dev" 
Thx!

**Comment by michaelrsweet** [comment]
Near as I can tell, this is an incompatibility between the PNG I bundle with htmldoc and GCC 4.9... Short of finding a workaround I can include, I think I'll just have to recommend using the system PNG library.
