### ISSUE TITLE
HTMLDoc stuck in windows 2008R2 while converting html to pdf using Runtime.exec() command

### ISSUE THREAD

**Issue by kiranJ0927** [michaelrsweet/htmldoc#319]
I have a strage issue with HTMLdoc to convert the HTML to pdf . 
I been able to convert html to pdf using HTMLDoc (version 1.8.27.1) in windows 7 machine. I cam calling the HTML doc from my java code using the Runtime.exec() to call the HTMLDoc. It is perfectly working fine on Windows 7. The Same code base, i try to run it on windows 2008 R2,it is not working.i see the htmldoc exe in the task manager with zero cpu and some memory and it stuck there for ever,unless i kill it.Iam just wondering why it is happening only on wondows 2008R2.is there any special setup required for this to run .Initially i thought the issue is with java Runtime.exec(), and i tried to pass other commands to execute on the same machine,same code base but different command to execute,which was working fine.

I see some issue with HTMLDoc with windows 2008R2.Not sure if iam missing anythign here. i appreciate if somebody help me with this.

thanks
kiran

**Comment by kiranJ0927** [comment]
command i was using to pass into Runtime.exec() was

String mycmd =  "cmd /c D:\\HTMLDOC\\htmldoc -quiet --webpage --datadir D:\\HTMLDOC\\ -f D:\\PDFs\\15894372_confirm.pdf D:\\HTML\\894372_Reg13RNov_HtmlOutput.html";
Process p = Runtime.getRuntime().exec(mycmd);
BufferedInputStream testOutput= new BufferedInputStream(p.getInputStream());
		int read = 0;
		byte[] output = new byte[1024];
		while ((read = testOutput.read(output)) != -1) {
		    System.out.println(output[read]);
		}

Also tried using ProcessBuilder instead of  Runtime.getRuntime().exec(). 

It seems to stuck at getting inpursteam. and never ends the htmldoc process in the task manager.

**Comment by michaelrsweet** [comment]
Your command is reading HTML from a file and sending the PDF output to a file. Any other diagnostic output will go to the standard error stream. The input stream would be for piping HTML *into* htmldoc, assuming that you specified "-" as the input.

Also, if the Java code is running on the web server, it is possible the environment is making htmldoc think it should be running in CGI mode...
