### ISSUE TITLE
Images not rendered in PDF when URL is HTTPS

### ISSUE THREAD

**Issue by vijaysankarv** [michaelrsweet/htmldoc#321]
Hi,

We are facing one issue in HTML to PDF conversion when the HTML content has an image served by HTTPS url in our domain. the HTTP URL for the same works fine.

I tried using the version v1.9.1 as suggested by you. The following error message is shown and the image is not rendered

**ERR010: Unable to connect to (our domain)!**

we tried using it on Windows 7

**Comment by vijaysankarv** [comment]
To add on, we tried using it on Windows 7

**Comment by michaelrsweet** [comment]
First, I'll need to see some HTML that is failing.

Also, have you checked the logs on the server for error messages (from the web server)?

**Comment by michaelrsweet** [comment]
@vijaysankarv Any chance of getting the HTML or server logs?
