### ISSUE TITLE
Wrong empty space behind orphan paragraphs with aligned image within

### ISSUE THREAD

**Issue by kcclarkson** [michaelrsweet/htmldoc#322]
Converting HTML to PDF with HTMLDOC 1.9.1/Win, if a paragraph with an aligned image within (\<p><img align=left ...) does not fit onto a page, HTMLDOC generates pretty much empty space at its end, see illustration. HTML file and resulting PDF file attached. Any help?
![screen](https://user-images.githubusercontent.com/36114287/35771297-a2baaa4e-092a-11e8-9858-efd53b71509d.png)
[html.zip](https://github.com/michaelrsweet/htmldoc/files/1692174/html.zip)
[test.pdf](https://github.com/michaelrsweet/htmldoc/files/1692170/test.pdf)
![test](https://user-images.githubusercontent.com/36114287/35771565-27bc7552-092f-11e8-89db-8c9a3c435173.gif)

**Comment by michaelrsweet** [comment]
Will look into it...

**Comment by michaelrsweet** [comment]
Reproduced!

**Comment by michaelrsweet** [comment]
[master 92de795] Fix formatting bug with aligned images (Issue #322)

(simple one-line fix)
