### ISSUE TITLE
One error remaining with aligned images (cf. issue #322)

### ISSUE THREAD

**Issue by kcclarkson** [michaelrsweet/htmldoc#324]
After applying bugfix related to issue #322, in almost all cases of wrapping paragraphs with aligned images the additional whitespace has been gone now. Thank you! However, every time the last text section is wrapped to the next page BEFORE the ps-pdf.cxx code passes below the aligned image, it will generate artificial whitespace again (and won't update the left margin, see illustration). I experienced that behaviour using spacer images (\<img src=spacer.gif height=10>) between divs, since the normal space of one line between paragraphs is to big for my purposes. Since this bug may depend from the screen resolution, it may be necessary to adapt the spacer height value used in the html file - a little bit more or less of height and everything is fine again ... All test files provided. I hope you can reproduce that error.
![illustration02](https://user-images.githubusercontent.com/36114287/36044719-cd1f3fa4-0dd3-11e8-8512-d48df001ea34.gif)
[html02.zip](https://github.com/michaelrsweet/htmldoc/files/1712111/html02.zip)
[test02.pdf](https://github.com/michaelrsweet/htmldoc/files/1712112/test02.pdf)

**Comment by michaelrsweet** [comment]
OK, I think I have this one (and a related formatting bug) fixed in:

[master 3bf56f6] Fix another aligned image bug (Issue #324)

**Comment by kcclarkson** [comment]
Thank you very much, Michael. Everything works now as expected.
