### ISSUE TITLE
Support AES encryption

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#325]
Add support for AES encryption.

**Comment by michaelrsweet** [comment]
Looks like the following code will provide what we need for PDF 1.6 128-bit AES support:

https://github.com/kokke/tiny-AES-c

**Comment by birdwes** [comment]
Hi Michael,

I've been looking at the PDF 1.7 standard  https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf
and it says it uses PKCS #7 padding in AES CBC mode.  Does that open up every single AES encrypted document to a Padding Oracle attack?

**Comment by michaelrsweet** [comment]
@birdwes Potentially, yes. PDF encryption really isn’t that strong, which is one of the reasons why I haven’t made adding AES support a high priority.

**Comment by michaelrsweet** [comment]
... and for PDF 2.0 they changed how encryption is done. In addition, macOS and iOS do not natively support 256-bit encryption of PDFs.

For this and the general weakness of PDF encryption, I have decided to dump this issue. If things change in the future I can always revive it...
