### ISSUE TITLE
Won't compile on Amazon Linux

### ISSUE THREAD

**Issue by FuzzyThailand** [michaelrsweet/htmldoc#326]
Downloaded 1.9.2 and ran configure followed by make. Getting a flood of these:

png.c:3873:19: error: unknown type name ‘png_structrp’
 png_gamma_correct(png_structrp png_ptr, unsigned int value,
                   ^
png.c:3898:23: error: unknown type name ‘png_structrp’
 png_build_16bit_table(png_structrp png_ptr, png_uint_16pp *ptable,
                       ^
png.c:3975:23: error: unknown type name ‘png_structrp’
 png_build_16to8_table(png_structrp png_ptr, png_uint_16pp *ptable,

Literally thousands of errors like the above.

Any particular library that is missing?

**Comment by FuzzyThailand** [comment]
config.status is here: https://pastebin.com/XzJtQ9yM

**Comment by michaelrsweet** [comment]
A copy of the make output might be useful, as would the version of compiler you are using.

**Comment by FuzzyThailand** [comment]
There it is (I thought config.status would have this data, sorry):

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-amazon-linux/4.8.3/lto-wrapper
Target: x86_64-amazon-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,fortran,ada,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-amazon-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-amazon-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-amazon-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) 


configure & make output is here:  https://pastebin.com/4kTZdupb

**Comment by michaelrsweet** [comment]
@FuzzyThailand please let me know if this is still an issue for you...
