### ISSUE TITLE
Where to find signing key?

### ISSUE THREAD

**Issue by reinerh** [michaelrsweet/htmldoc#327]
Hi,
I noticed that you started to sign the releases since version 1.9.2, which is really cool.
But I'm unable to find the key with which they have been signed.

> $ gpg --verify *.sig
> gpg: assuming signed data in 'htmldoc-1.9.2-source.tar.gz'
> gpg: Signature made Sat 03 Feb 2018 08:41:46 PM CET
> gpg:                using RSA key 845464660B686AAB36540B6F999559A027815955
> gpg: Can't check signature: No public key
> $ gpg --recv-keys 845464660B686AAB36540B6F999559A027815955
> gpg: keyserver receive failed: No data

I was not able to find that key on any keyserver.
Can you please tell me where to get it?

**Comment by michaelrsweet** [comment]
@reinerh I've had a hell of a time getting my PGP keys on the various public PGP key servers (the Mac PGP tools don't seem to support uploading, and the various web front ends keep timing out for me as well...), but I've put up a [page](http://www.msweet.org/pgp.html) on my web site with the public key you can import locally for verification.
