### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by reinerh** [michaelrsweet/htmldoc#330]
Can you please clarify the license of the font files?
The ones from URW seem to be GPL-licensed, but for the Bitstream font files, I can only find the following statement:
```
Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved.
DejaVu changes are in public domain
```

**Comment by michaelrsweet** [comment]
The font files use their own licenses. In the case of DejaVu, Bitstream is providing them as freely as possible (not every country as a notion of "public domain", but their intent is to provide them to everyone with no restrictions.
