### ISSUE TITLE
HTMLDOC Not start on iMac

### ISSUE THREAD

**Issue by VincenzoCorrado** [michaelrsweet/htmldoc#333]
I have installed htmldoc on my new brad iMac 5K 2017. Launching the application nothing happens.
I have installed htmldoc by dragging the app in my application folder.
Can you help me ?

Best regards 
Vincenzo Corrado

**Comment by michaelrsweet** [comment]
Are you getting any errors listed in the Console utility?

**Comment by VincenzoCorrado** [comment]
It seems there are not anything about htmldoc on console.
What I have to search exactly ?
My OS is High Sierra.





On 5 giugno 2018 a 18:46:03, Michael R Sweet (notifications@github.com<mailto:notifications@github.com>) scritto:

Are you getting any errors listed in the Console utility?

**Comment by michaelrsweet** [comment]
Please comment if the problem was resolved by the new disk image....
