### ISSUE TITLE
Images sometimes getting loaded and sometimes not in the pdf

### ISSUE THREAD

**Issue by jaysb29** [michaelrsweet/htmldoc#335]
We have our images stored on the EFS. The problem is sometimes the images are available and sometimes not. I found this is due to the image taking time to load from the EFS. Is there something I can do so that my pdfs not downloaded until all the images are rendered in the pdf

**Comment by michaelrsweet** [comment]
As long as HTMLDOC doesn’t get an error back from the server it should wait. What errors are being reported during conversion?

**Comment by jaysb29** [comment]
No errors are being reported during the conversion. It just downloads the pdf. I am using absolute url for including the images

**Comment by michaelrsweet** [comment]
@jaysb29 How are you running HTMLDOC?

**Comment by jaysb29** [comment]
$cmd  = " --left $x_margin --right $x_margin --top $y_margin --bottom $y_margin";
				$cmd .= " --header ... --footer $footer --quiet --jpeg --color";
				$cmd .= " --bodyfont $font --fontsize $size --linkstyle plain --linkcolor $linkcol";
				$cmd .= " --format pdf14 $layout $width --titlefile $titlepagefile --size letter";
				$cmd  = "htmldoc -t pdf --book --charset iso-8859-1 --webpage --no-numbered $cmd $file > " . escapeshellarg($pdfFileName);
			}else

**Comment by michaelrsweet** [comment]
Ok, for starters “—webpage” overrides “—book”. Just use one.

Output should not be sent to stdout with the shell redirect, just specify “-f outfile”.

It looks like you are using PHP, what operating system and version of PHP?

Can you attach some sample HTML?

**Comment by jaysb29** [comment]
Using PHP 7. Sure will attach the html as welll

**Comment by michaelrsweet** [comment]
@jaysb29 *ping*

**Comment by jaysb29** [comment]
After checking my html content, I have observed that images with http are getting rendered and images with https are not getting rendered in the pdf.
I create a sample content where I accessed same image with http and https protocol. Http image got rendered in the pdf and https not

**Comment by michaelrsweet** [comment]
What operating system?

Did you compile from source or are you using binaries from somewhere?

**Comment by michaelrsweet** [comment]
Please run the current 1.9.4 release rather than a 12-year-old snapshot of 1.8.27 - it has a lot of known security bugs and an obsolete HTTPS stack that is probably the cause of this issue...

**Comment by jaysb29** [comment]
Thankyou
