### ISSUE TITLE
Document HTTPS requirements and throw an error when not available

### ISSUE THREAD

**Issue by rodolfojcj** [michaelrsweet/htmldoc#339]
Hi.

I'm wondering why I can't get that generated PDF files have images when created by htmldoc 1.9.4.

Given a file named simple.html with this content:
 
    <!DOCTYPE html>
    <html>
    <head>Hunting a bug with images and htmldoc</head>
    <body>
      <p>Before</p>
      <img align="left" src="https://i.pinimg.com/736x/39/07/26/39072670fcd89ee47d32ce00d7e22030--logo-travel-design-travel-logos.jpg" />
      <img align="left" src="https://www.deluxe.com/sites/www.deluxe.com/files/logo_design/logo/logo-samples-28-300x300.png" />
      <p>After</p>
    </body>
    </html>

When using the following command with htmldoc version 1.9.4:

    htmldoc --verbose --continuous --webpage --jpeg=0 -t pdf14 --size universal --no-strict -f simple_1.9.4.pdf simple.html

the resulting PDF file simple_1.9.4.pdf does not include the images.

But if I use htmldoc version 1.8.27 with this command:

    htmldoc --verbose --continuous --webpage --jpeg=0 -t pdf14 --size universal --no-strict -f simple_1.8.27.pdf simple.html

the resulting PDF file simple_1.8.27.pdf does successfully include the images.

It's the same machine, no network connectivity problems were found to get the images, different images from different sources and with different formats were used and no command line errors were received in the shell terminal.

Some details about the execution environment:

- Debian GNU/Linux 9
- Kernel 4.9.0-4-amd64
- htmldoc 1.8.27-8+b5 installed from operating system packages
- htmldoc 1.9.4 manually installed from sources
- gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

Could you please help me with that?

Also, if you need something that I can help with to solve this, please let me know.

Thanks in advance.

**Comment by rodolfojcj** [comment]
@michaelrsweet Thanks for answering.

In fact, the `libgnutls28-dev` was not installed.

For the sake of completeness I want to add these notes:

- Let's take the full htmldoc sources for revision a648b311479a84aea640771414192a7cf8edfb97, which I downloaded as the master revision some minutes ago
- Let's take the following modified simple.html that includes http and https images links

```
    <!DOCTYPE html>
    <html>
    <head>Hunting a bug with images and htmldoc</head>
    <body>
      <p>Before</p>
      <img src="https://i.pinimg.com/736x/39/07/26/39072670fcd89ee47d32ce00d7e22030--logo-travel-design-travel-logos.jpg" />
      <img src="https://www.deluxe.com/sites/www.deluxe.com/files/logo_design/logo/logo-samples-28-300x300.png" />
      <img src="http://gloria-project.eu/wp-content/uploads/2012/06/logo-256-transp.png" />
      <p>After</p>
    </body>
    </html>
```

- Let's use the same `htmldoc` commands I mentioned in my [original issue description](https://github.com/michaelrsweet/htmldoc/issues/339#issue-382491212)
- With htmldoc sources compiled without installing `libgnutls28-dev` Debian package, the generated PDF file doesn't include the two images linked via https, but include the image that uses http
- After installing `libgnutls28-dev` package version 3.3.30-0+deb8u1 for Debian 8, I recompiled htmldoc sources and generated a new PDF file, observing that this time all the three images are included. This solves the problem I experienced

Can you tell me from which htmldoc version the installation of `libgnutls28-dev` is a must to be able to process https links? With htmldoc 1.8.27 that was not the case.

Could you please add in the README file a brief note to highlight the need of that package dependency to properly handle https links in newer htmldoc versions?

Thanks again Michael!

**Comment by michaelrsweet** [comment]
HTMLDOC 1.8.29 dropped OpenSSL support - this is listed in the CHANGES.md file.

But I will add a list of dependencies to INSTALL.md so that it is explicit, and maybe referencing a HTTPS URL when no SSL support is compiled in should generate an error.

**Comment by michaelrsweet** [comment]
Just confirmed that referencing a https URL when there is no SSL support does, in fact, generate an error message:

    ERR005: Unable to find "https://foo/bar"...

**Comment by michaelrsweet** [comment]
OK, I added a little note to the --help output, as well as more detailed instructions in INSTALL.md.

[master df230b1] Report whether HTTPS URLs are supported (Issue #339)

**Comment by alexgoa** [comment]
Hello, I've the same issue in generating pdf using https. 
I've just upgraded to htmldoc 1.9.7 from 1.8.27
I'm using a windows 2019 server with Plesk Obsidian on board and Let's Encrypt certificate. 
What should I do to generate pdf?
Thanks 
Alessandro
