### ISSUE TITLE
Enable embedded image source

### ISSUE THREAD

**Issue by prsbrc** [michaelrsweet/htmldoc#340]
Hallo.
Is it possible to enable embedded images like
`<img src="data:image/png;base64,iVBORw0KG..."/>` ?

Thanks!
Christian

**Comment by michaelrsweet** [comment]
Will consider, although IIRC data URIs are deprecated for security reasons.

**Comment by prsbrc** [comment]
Thx a lot

**Comment by michaelrsweet** [comment]
[master 07f367c] Add support for data URIs (Issue #340)
