### ISSUE TITLE
Can't compile htmldoc 1.9.4 from sources on CentOS 6.10

### ISSUE THREAD

**Issue by rodolfojcj** [michaelrsweet/htmldoc#341]
When trying to install htmldoc version 1.9.4 from sources on CentOS 6, I'm seeing several error messages like the following ones:

    png.h:500: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘png_structrp’
    png.c:4338: error: expected ‘)’ before ‘png_ptr’

Maybe the installed packages on that operating system are too outdated, however I want to be sure that's the cause.

I'm attaching these files:

- [error_centos_6.10_htmldoc_1.9.4.txt](https://github.com/michaelrsweet/htmldoc/files/2753599/error_centos_6.10_htmldoc_1.9.4.txt) containing the detailed error output I'm getting
- [centos_6.10_installed_rpm_packages.txt](https://github.com/michaelrsweet/htmldoc/files/2753600/centos_6.10_installed_rpm_packages.txt)
 containing the full list of installed packages on my CentOS 6 test machine

To verify this by yourself, you can use a virtual machine based on that operating system version.

Thanks in advance for your time and attention.

**Comment by michaelrsweet** [comment]
The issue is the version of GCC that you have installed isn't compatible with the (newer) version of libpng that is included with the HTMLDOC sources. Try installing libpng-dev first and then it should build just fine.

**Comment by rodolfojcj** [comment]
Hi Michael.

Thanks for answering.

In fact you are right. Running the command `yum install libpng-devel` and then trying again with the HTMLDOC installation worked fine.

Thanks again.

**Comment by rodolfojcj** [comment]
With Debian 8 the same described issue happens. The solution is also to install the development package of libpng, via the following command:

    apt-get install libpng-dev

which is a virtual package that installs `libpng12-dev` for that distribution.
