### ISSUE TITLE
[v1.9.5] Source files have everything on the top level directory prefixed with `htmldoc-1.9.5`

### ISSUE THREAD

**Issue by dbermond** [michaelrsweet/htmldoc#342]
The sources files [htmldoc-1.9.5-source.tar.gz](https://github.com/michaelrsweet/htmldoc/releases/download/v1.9.5/htmldoc-1.9.5-source.tar.gz) and [htmldoc-1.9.5-source.zip](https://github.com/michaelrsweet/htmldoc/releases/download/v1.9.5/htmldoc-1.9.5-source.zip) have everything on the top level directory prefixed with `htmldoc-1.9.5`. This does not reflect the source tree. These two files are the ones provided for use with the PGP key validation.

`ls` output of these source files:
```
$ mkdir htmldoc-1.9.5
$ cd htmldoc-1.9.5
$ curl -o htmldoc-1.9.5-source.tar.gz https://github.com/michaelrsweet/htmldoc/releases/download/v1.9.5/htmldoc-1.9.5-source.tar.gz
$ bsdtar -xf htmldoc-1.9.5-source.tar.gz
$ ls -l | awk '{ print $NF }' | sed '1d'
htmldoc-1.9.5cgi-bin
htmldoc-1.9.5CHANGES.md
htmldoc-1.9.5config.h.in
htmldoc-1.9.5configure
htmldoc-1.9.5configure.ac
htmldoc-1.9.5COPYING
htmldoc-1.9.5data
htmldoc-1.9.5desktop
htmldoc-1.9.5dmgbuild.png
htmldoc-1.9.5dmgbuild.py
htmldoc-1.9.5doc
htmldoc-1.9.5fonts
htmldoc-1.9.5htmldoc
htmldoc-1.9.5INSTALL.md
htmldoc-1.9.5install-sh
htmldoc-1.9.5jpeg
htmldoc-1.9.5Makedefs.in
htmldoc-1.9.5Makefile.in
htmldoc-1.9.5png
htmldoc-1.9.5README.md
htmldoc-1.9.5snap
htmldoc-1.9.5SNAPCRAFT.md
htmldoc-1.9.5vcnet
htmldoc-1.9.5xcode
htmldoc-1.9.5zlib
```

The source files automatically generated by github for the 1.9.5 release are fine.

**Comment by michaelrsweet** [comment]
OK, updated archives have been uploaded...
