### ISSUE TITLE
Setup Travis CI for build AppImage package for Linux

### ISSUE THREAD

**Issue by Symbian9** [michaelrsweet/htmldoc#343]
AppImage for Linux is same as DMG for macOS

- http://github.com/appimage/appimagekit
  - http://github.com/probonopd/linuxdeployqt
  - http://github.com/probonopd/uploadtool

Here is example of `.travis.yml` set for providing AppImage

- https://github.com/KurtPfeifle/htmldoc/blob/master/.travis.yml

If you need any help with AppImage build scrip ask @probonopd

**Comment by michaelrsweet** [comment]
I'm not keen on adding yet another package format right now. We already support snaps...

Holding for later...

**Comment by michaelrsweet** [comment]
Since Travis CI is no longer free to use, closing this...

**Comment by Symbian9** [comment]
> Since Travis CI is no longer free to use

It still is free to use, see:

- https://github.com/leozide/leocad/blob/master/.travis.yml
  - https://github.com/leozide/leocad/releases/tag/continuous

**Comment by probonopd** [comment]
Would you be interested in having this ported over to GitHub Actions?

**Comment by Symbian9** [comment]
To be clear, this is *request for AppImage builds* of HTMLDOC (so actual feature request issue should be reopened)

It should be no matter which way AppImage would be built: on Travis, GitHub Actions or any other CI.
