### ISSUE TITLE
Remove Pdf Bookmark

### ISSUE THREAD

**Issue by PaulGambke** [michaelrsweet/htmldoc#344]
Hi Michael,

there seems to be some change from the version 1.8.22 to the current version regarding the creation of bookmarks.
When I use a single input file and set the document type to "Web Page", before there were no bookmarks in the resulting PDF.
In the version 1.9.3 the PDF always has one bookmark with the title of the HTML page, or if no title is found, the filename.
Is there a way to remove this bookmark? I didn't find any setting to get rid of it.

Thanks!
Paul

**Comment by michaelrsweet** [comment]
[master c059e9d] Stop emitting a PDF outline tree if we only have one thing to outline (Issue #344)
