### ISSUE TITLE
1.8.23 Performance decline

### ISSUE THREAD

**Issue by ninad1999** [michaelrsweet/htmldoc#345]
Hi Michael,

I am currently using version 1.8.23 of htmldoc as a tool in my application to convert html to pdf. Its a great tool! Thank you for creating it! 
I started having issues when I upgraded the servers, from 32 bit to 64 bit. The time taken for the conversion from html to pdf increased by 2-3 times. Is this a problem with the version compatibility and will upgrading to a newer version of htmldoc fix that issue? Whats your viewpoint on this?

Thanks
Ninad

**Comment by michaelrsweet** [comment]
First, 1.8.23 is *ancient*. It was unsupported when Easy Software Products was still a company and started selling 1.8.24.

Second, running 32-bit binaries on a 64-bit system will be slow, particularly with the various Spectre/etc. "fixes" that MS has adopted.

All that said, you'll almost certainly find the current 1.9.x HTMLDOC as fast or faster than 1.8.23 used to be, particularly if you get a 64-bit build. Right now I'm not providing Windows builds (can't get a commercial code signing certificate as an individual in Canada, and the current project files only create 32-bit installers) but you can use the free version of Visual Studio with the project files included with the HTMLDOC sources to build a 64-bit version of your own...

**Comment by ninad1999** [comment]
Hi michael. I was trying to install version 1.9.5 using visual studio. The build is successful for 4 projects but fails for ghtmldoc and gives error: LNK1104 : cannot open file 'md/fltk.lib'. How t fix that? Also in install.md when you say "You must add the FLTK include and library directories separately for the solution to build." what does that mean?

**Comment by michaelrsweet** [comment]
You'll find FLTK at <https://www.fltk.org>, with a corresponding Github project. Unfortunately I'm not aware of a Nuget package you can use... :/

**Comment by ninad1999** [comment]
hi micheal, when i downloaded the 1.9.5 source code,  there was already a fltk 1.3.3.33 folder in the packages folder in vcnet. I see that it includes some .lib files. Do I have to download a fltk from https://www.fltk.org apart from the fltk 1.3.3.33 included in the packages, and add it to the packages folder?

**Comment by michaelrsweet** [comment]
No if you have a flak package available that should be enough. Just reference it for the ghtmldoc target in the project.
