### ISSUE TITLE
Htmldoc 1.9.4 not working with urls.

### ISSUE THREAD

**Issue by kiran0927** [michaelrsweet/htmldoc#347]
I been trying to work with 1.9.4 .i am not seeing the request is reaching the server/application to download the HTML and convert it to PDF.same thing works with 1.8.27.not sure what issue with 1.9.4 using url. 1.9.4 works with HTML file ,but not with url.

Any pointers to debug.

Htmldoc -t PDF -f mysample.pdf --webpage url

This is the command IAM trying..

Url is https and same is working with 1.8.27.

Please help with this as I stuck here since few days without anyluck

**Comment by kiran0927** [comment]
Error says "No HTMLs"

Request is not invoking or reaching the application

**Comment by michaelrsweet** [comment]
@kiran0927 What kind of URL are you using, i.e., are they 'https://...' or 'http://...'?

What operating system?

Did you compile from source or are you using a pre-built binary?

**Comment by kiran0927** [comment]
Hello Michael,

Many thanks for responding and I am very happy to see your response.

Our admin team compiled it and installed on linux.we areable to convert
normal HTMLs to PDFs.so they are saying the installation is sucessf.but
when I try with a webpage url it is not working.i see no issues with
webpage when I try to display with curl command on the same box.

For http/https requests as --webpage, htmldoc is not  working and Wondering
what would be the issue.would there be any configuration that we missed or
any issue with installation?



After installation ,I see bin folder with htmldoc and some other folder( I
think it is 'share'folder..I have to on my server box..).nothing else.

But the same html webpage is working with htmldoc 1.8.27 version on the
same box.

Let me know if you need more details


Please give some pointers to check my installation and configuration.

Are there any special instructions for compiling the code on Linux.if there
is any link to do it please let me know.

Thanks again for responding.


Thanks
Kiran

**Comment by kiran0927** [comment]
Sorry forgot to answer one thing..I tried https not http.

Thanks
Kiran

**Comment by michaelrsweet** [comment]
Make sure your admin had installed the GNU TLS developer package - HTMLDOC 1.8.27 still supported OpenSSL but HTMLDOC 1.8.29 and later only support GNU TLS.

**Comment by kiran0927** [comment]
Micheal,

Many thanks as for the quick response.i will make sure we have TLS
installed and check.

Can you give me link to the detailed compilation and installation
instructions if available.


Thanks
Kiran

**Comment by michaelrsweet** [comment]
See the [INSTALL.md](https://github.com/michaelrsweet/htmldoc/blob/master/INSTALL.md) file.

**Comment by kiran0927** [comment]
Hi Micheal,

Once installed GnuTLS ,are there any setup instructions for HTMlLdoc to
configure .

Thanks
Kiran

**Comment by michaelrsweet** [comment]
No, just running the configure script will find the installed libraries htmldoc needs...
