### ISSUE TITLE
dissapear letters

### ISSUE THREAD

**Issue by RekGRpth** [michaelrsweet/htmldoc#348]
command
```sh
htmldoc --bodyfont Sans --charset utf-8 --webpage -f test.pdf --header . --footer . test.html
```
1) content of test.html
```html
<html><body>
йцукенгшщзхъфывапролджэячсмитьбюё<br/>
ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮЁ<br/>
съешь ещё этих мягких французских булок да выпей чаю<br/>
СЪЕШЬ ЕЩЁ ЭТИХ МЯГКИХ ФРАНЦУЗСКИХ БУЛОК ДА ВЫПЕЙ ЧАЮ<br>
</body></html>
```
result [test.pdf](https://github.com/michaelrsweet/htmldoc/files/3011498/test.pdf)
![1](https://user-images.githubusercontent.com/3190488/55051029-50e39a80-5075-11e9-87c9-7d4fdd5e5efd.png)
2) content of test.html
```html
<html><body>
съешь ещё этих мягких французских булок да выпей чаю<br/>
СЪЕШЬ ЕЩЁ ЭТИХ МЯГКИХ ФРАНЦУЗСКИХ БУЛОК ДА ВЫПЕЙ ЧАЮ<br>
</body></html>
```
result [test.pdf](https://github.com/michaelrsweet/htmldoc/files/3011499/test.pdf)
![2](https://user-images.githubusercontent.com/3190488/55051042-65c02e00-5075-11e9-8bac-f258acc45c51.png)

**Comment by michaelrsweet** [comment]
My guess is the font is missing some characters - I’ll investigate when I have a chance...

**Comment by RekGRpth** [comment]
but with some conditions letters are exists and with other conditions the same letters are not exists!

**Comment by RekGRpth** [comment]
I also try liberation fonts - result is same :(

**Comment by michaelrsweet** [comment]
Well, I was able to reproduce but I don't know why this is happening. Investigating...

**Comment by RekGRpth** [comment]
I discovered, that 33th unique symbol disappears always

**Comment by RekGRpth** [comment]
file
```html
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
```
give
![test](https://user-images.githubusercontent.com/3190488/57669123-3bc1cb80-7623-11e9-8437-92eefa4ab52f.png)

**Comment by RekGRpth** [comment]
file
```html
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
абвгдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<br/>
```
give
![test](https://user-images.githubusercontent.com/3190488/57669202-7297e180-7623-11e9-8b17-72e49b0050c3.png)

**Comment by RekGRpth** [comment]
file
```html
ааббввггдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
ААББВВГГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<BR/>
ааббввггдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
ААББВВГГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<BR/>
ааббввггдеёжзийклмнопрстуфхцчшщъыьэюя<br/>
ААББВВГГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ<BR/>
```
give
![test](https://user-images.githubusercontent.com/3190488/57669275-bc80c780-7623-11e9-95f2-c0202478613b.png)

**Comment by RekGRpth** [comment]
I found, where bug occurs!
```c
      if (*s == 160) /* &nbsp; */
      {
	if (compress)
          flate_write(out, (uchar *)" ", 1);
	else
          putc(' ', out);
      }
```
utf-8 chars starts at 128, and 160 is 33th after 128! and it changed to space!

**Comment by michaelrsweet** [comment]
@RekGRpth Good catch! I'll work out a fix soon...

**Comment by michaelrsweet** [comment]
[master 6c1ab0c] Fix UTF-8 missing characters (Issue #348)

**Comment by slobo** [comment]
I think this could have broken `&nbsp;` support

`cat test.html`
```
<html><body>
hello,&nbsp;world = ćao,&nbsp;svete
</body></html>
```

In the resulting [test.pdf](https://github.com/michaelrsweet/htmldoc/files/5253522/test.pdf), nbsp got replaced by the first utf-8 character it found:

![image](https://user-images.githubusercontent.com/167772/93734360-de7e4880-fb8d-11ea-9ae9-813c734bdcf6.png)

**Comment by RekGRpth** [comment]
> nbsp got replaced by the first utf-8 character it found

Yes, I confirm this bug :(

**Comment by RekGRpth** [comment]
> nbsp got replaced by the first utf-8 character it found

Yes, I confirm this bug :(
but not `first utf-8 character it found`, but `first utf-8 character it found after &nbsp;`

in
```
Здравствуй,&nbsp;мир! = До свидания,&nbsp;мир!
```

out 
![out](https://user-images.githubusercontent.com/3190488/93736477-ebd11c80-fbf9-11ea-968a-723520b88db7.png)

**Comment by slobo** [comment]
While this is most likely a wrong fix (I suspect that it will not correctly format non-breaking spaces), I'll just include it here in case it helps with real fix, as it does eliminate the "utf-8 character instead of nbsp" bug

```diff
diff --git a/htmldoc/iso8859.cxx b/htmldoc/iso8859.cxx
index 98ee339..2929825 100644
--- a/htmldoc/iso8859.cxx
+++ b/htmldoc/iso8859.cxx
@@ -188,7 +188,7 @@ static lut_t	iso8859_numbers[] =
 		  { "minus",	8722 },
 		  { "mu",	956 },
 		  { "nabla",	8711 },
-		  { "nbsp",	160 },
+		  { "nbsp",	0x20 },
 		  { "ndash",	8211 },
 		  { "ne",	8800 },
 		  { "ni",	8715 },
diff --git a/htmldoc/ps-pdf.cxx b/htmldoc/ps-pdf.cxx
index af1a55e..097c6c7 100644
--- a/htmldoc/ps-pdf.cxx
+++ b/htmldoc/ps-pdf.cxx
@@ -12023,15 +12023,15 @@ write_string(FILE  *out,		/* I - Output file */
   }
   else
   {
-    uchar nbsp = 160;			// Non-breaking space char
+    uchar nbsp = 0x20;			// Non-breaking space char
 
     if (compress)
       flate_write(out, (uchar *)"(", 1);
     else
       putc('(', out);
 
-    if (_htmlUTF8)
-      nbsp = _htmlCharacters[160];
+//     if (_htmlUTF8)
+//       nbsp = _htmlCharacters[160];
 
     while (*s != '\0')
     {
```

I do notice there were some other places in code that use magic number `160`, i.e. character width is also set to the wrong width on utf-8 input, but I'm not familiar with htmldoc code to have ventured any closer to a real fix™

**Comment by RekGRpth** [comment]
I found another solution! Because with `&nbsp;` there is a bug, but with unicode character `0xA0` - NOT
```diff
diff --git a/htmldoc/iso8859.cxx b/htmldoc/iso8859.cxx
index 2734ec5..194243d 100644
--- a/htmldoc/iso8859.cxx
+++ b/htmldoc/iso8859.cxx
@@ -376,6 +376,13 @@ iso8859(uchar *name)                       /* I - Glyph name */
            }
          }
 
+      if (_htmlUTF8) {
+        int unicode = _htmlUTF8++;
+        _htmlCharacters[ch]   = (uchar)unicode;
+        _htmlUnicode[unicode] = ch;
+        _htmlGlyphs[unicode]  = _htmlGlyphsAll[ch];
+      }
+
          // Return the new character...
          return ((uchar)newch);
        }
```

**Comment by michaelrsweet** [comment]
@RekGRpth OK, so I think you are on the right path for the fix, but I think that function actually needs to explicitly handle UTF-8 instead.

**Comment by michaelrsweet** [comment]
Tracking the regression in issue #401.
