### ISSUE TITLE
Link to PDF Named Destination anchor point in External URL

### ISSUE THREAD

**Issue by nbjones57** [michaelrsweet/htmldoc#351]
Hi Martin,
Thankyou for HTMLDOC! I find it invaluable as part of my on-line help to PDF Manual conversion.

I have a new feature request...
HTMLDOC can generate a link in the output PDF to an external file (filename.pdf) or internal (#target) link. Would it be possible to generate a link to a Named Destination (anchor) point within an external file if that external file is of type "PDF" (or any type other than HTML)?
e.g.
 \<A HREF="filename.pdf#tag"\>... \</A\>

This link to the named destination "tag" in the PDF document "filename.pdf" is supported in HTML browsers. However, HTMLDOC 9.3 treats this as:

 \<A HREF="#tag"\>... \</A\>

i.e. a link to "tag" in the current (generated) PDF document.

**Comment by michaelrsweet** [comment]
This has been requested a few times now. I’m not sure that I can encode a named link target for a PDF file, but will review things when I get a chance.

**Comment by michaelrsweet** [comment]
Looks like the D key (destination) can be a name string, so will try adding support for that.
