### ISSUE TITLE
HTMLDOC Executable

### ISSUE THREAD

**Issue by gkmundt** [michaelrsweet/htmldoc#353]
I downloaded htmldoc-1.9.5-source tar.gz and put it on a new 64-bit server, but I don't have an HTMLDOC executable.  When I try to extract and type configure I am getting a permissions issue even though I am logged in as root.  Is there a specific download I should use for 64-bit?

**Comment by michaelrsweet** [comment]
The source archive does not contain executables for any operating system. The last version I packaged for windows was 1.9.3. I am working on a newer signed 64-bit installer for the next 1.9.x release...
