### ISSUE TITLE
Shared lib (feature request)

### ISSUE THREAD

**Issue by RekGRpth** [michaelrsweet/htmldoc#355]
How about shared lib?
I made own version of shared lib in my [fork](https://github.com/RekGRpth/htmldoc), but it very bad.
I use it in [nginx](https://github.com/RekGRpth/ngx_http_htmldoc_module), [postgres](https://github.com/RekGRpth/pg_htmldoc) and [python](https://github.com/RekGRpth/pyhtmldoc)

**Comment by michaelrsweet** [comment]
The current code really wasn't written with embedding as a library in mind, so I'm not inclined to try to do it as-is.

I have another project (working on it sporadically) that *is* designed as a library - [htmlcss](https://github.com/michaelrsweet/htmlcss) - and my thinking is that, at some point in the future, this might form the core of a new HTMLDOC rendering/conversion library you could embed.
