### ISSUE TITLE
page size not increasing even when using page size attribute in command

### ISSUE THREAD

**Issue by tchavali** [michaelrsweet/htmldoc#359]
Hi,

--webpage --no-strict --left .15in --top .25in --bottom .25in --size 11x14in --browserwidth 1000 --header ... --footer ... --linkcolor #0000ff -f " + outputFileName + " " + tempFile;

I am trying to increase the size of the page in landscape mode when some of the content is getting cut off when converting from html to pdf.

I am using above command for that, but it is still not increasing the page size. Could you please advice?

Thanks

**Comment by michaelrsweet** [comment]
@tchavali The file didn't attach - you might need to rename it with a ".txt" extension...
