### ISSUE TITLE
table many columns bug

### ISSUE THREAD

**Issue by RekGRpth** [michaelrsweet/htmldoc#361]
1) test.html
```html
<table border="1" width="100%">
    <thead>
        <tr valign="middle">
            <th>Veryveryvery long header 1</th>
            <th>Veryveryvery long header 2</th>
            <th>Veryveryvery long header 3</th>
            <th>Veryveryvery long header 4</th>
            <th>Veryveryvery long header 5</th>
            <th>Veryveryvery long header 6</th>
            <th>Veryveryvery long header 7</th>
            <th>Veryveryvery long header 8</th>
            <th>Veryveryvery long header 9</th>
            <th>Veryveryvery long header 10</th>
        </tr>
    </thead>
</table>
```
2) command
```sh
htmldoc --charset utf-8 --header ... --footer ... --size a4 --outfile test.pdf test.html
```
3) test.pdf
[test.pdf](https://github.com/michaelrsweet/htmldoc/files/3558145/test.pdf)
4) test.png
![test](https://user-images.githubusercontent.com/3190488/63990796-c230e900-cafe-11e9-843d-380e1ec24c52.png)

**Comment by michaelrsweet** [comment]
Yeah, the table doesn't fit and HTMLDOC will not truncate/clip. You can use `<wbr>` to insert soft breaks where you'd like to see HTMLDOC break "veryveryvery" but that's about it.

**Comment by RekGRpth** [comment]
How about to support ```&shy;``` tag?

**Comment by michaelrsweet** [comment]
Will consider support for the &shy; entity...

**Comment by michaelrsweet** [comment]
[master ad31a76] Implement &shy; support (Issue #361)
