### ISSUE TITLE
Thin horizontal colored line

### ISSUE THREAD

**Issue by BartVanderDonck** [michaelrsweet/htmldoc#362]
I've found no way to draw a thin horizontal colored line:
- &lt;hr size="1" color="red"&gt;
- &lt;table bgcolor="red" height="1" cellspacing="0" cellpadding="0" border="0"&gt;&lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
- &lt;table cellspacing="0" cellpadding="0" border="0"&gt;&lt;tr&gt;&lt;td bgcolor="red" height="1"&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
- &lt;div bgcolor="red" height="1"&gt;&lt;/div&gt;
These all don't appear to work ... Would there be any possibility ? I was thinking about "_________" but it looks buggy and not elegant anyway.
Thank you, Bart

**Comment by michaelrsweet** [comment]
@BartVanderDonck The "classic" HTML way is using a 1x1 pixel image of the desired color, resized using the WIDTH and HEIGHT attributes, e.g.:

    <img src="red.gif" width="100%" height="1">
