### ISSUE TITLE
Makefile hangs 

### ISSUE THREAD

**Issue by hwpfeil** [michaelrsweet/htmldoc#363]
Makefile builds doc/pdf and doc/ps before it creates the install tree.  /tmp/htmldoc/htmldoc/htmldoc runs an infinite loop looking for fonts and data folders that do not yet exist. (Source extracted to /tmp/htmldoc.)
Making all in doc...
Formatting htmldoc.epub...
BYTES: 501992
Formatting htmldoc.html...
BYTES: 122422
Formatting htmldoc.pdf...
^^^^^^^^^^^^^^^ <<-- here's where "make all" hangs. Ctrl-c to break loop, then
cd doc
valgrind -v ../htmldoc/htmldoc --batch htmldoc.book -f htmldoc.pdf
...
ERR005: Unable to open font width file /tmp/htmldoc/usr/share/htmldoc/fonts/Dingbats.afm! <<-- for each font file in /tmp/htmldoc//fonts
ERR005: Unable to open psglyphs data file! <<-- that's in /tmp/htmldoc/data 
ERR005: Unable to open character set file iso-8859-1! <<-- that's also in the data folder
repeat until ctrl-c
/tmp/htmldoc/usr/share/htmldoc/fonts and /data do not yet exist.

Here's my configure command:
./configure \
  --prefix=/usr \
  --libdir=/usr/lib64  \
  --enable-ssl \
  --with-gui \
  --disable-localjpeg \
  --disable-localzlib \
  --disable-localpng \
  --disable-gnutls 

The disabled features are already installed. Same issue 1.8.29, 1.8.30. 1.9.5 and git clone.

**Comment by hwpfeil** [comment]
Problem:
DIRS =  htmldoc doc  <<-- Move "doc" to a separate build in Makefile.in
Solution:
Take "doc" out of DIRS and INSTALLDIRS.
add the following to the end of "install:" in Makefile.in
        done
+	$(MAKE) docs
+
+docs:
+	cd doc; $(MAKE) -$(MAKEFLAGS) || exit 1;

That fixes the fonts and data problem only if root invokes "make install" with no DESTDIR defined If there is a DESTDIR, then the install tree gets built under DESTDIR, but htmldoc still looks for fonts and data under /usr/share/htmldoc. If root does "make install" with no DESTDIR, a fatal flaw in htmldoc.cxx reveals itself. htmldoc::parse_options contains an if-else tree that depends on the uninitialized value of "temp", so the if-else tree falls through to another if-else tree that depends on the uninitialized value of "temp2" and "temp". My laptop stops executing at line 2143. The loop goes line 252 --> line 1833 --> each strcmp() up to 2143. Further analysis might show the stack segment colliding with the heap segment, I don't know. Valgrind just halts. When interrupted, it shows a definite memory leak. Hang at ps-pdf.cxx:5513. heap 1.7Mb,
32,100 not-freed blocks, no pointers to those not-freed blocks in 7Mb.
Suggest converting the if-else trees to case statements. Then there wouldn't be so many calls to strcmp(). The uninitialized values appear during stack allocation. Be sure to initialize the temp and temp2 arrays before testing them. The uninitialized values are indeterminate, depending on the machine's compiler implementation.
Cheers!

**Comment by michaelrsweet** [comment]
When making the documentation, the "--datadir .." option is passed in to pull the data files from the source directory, NOT the installation directory.

Will see if I can reproduce locally (but I haven't so far...)

**Comment by michaelrsweet** [comment]
OK, so this looks like a known compiler bug - issue #349

**Comment by hwpfeil** [comment]
It was valgrind that showed the "cannot find /usr/share/htmldoc/fonts" error.
Not a compiler bug. Using gcc/g++ 
Steps to reproduce:
 git clone --recursive https://github.com/michaelrsweet/htmldoc.git
configure && make
Hangs building pdf
cd doc && valgrind -v  ../htmldoc/htmldoc --batch htmldoc.book -f htmldoc.pdf
Result: screen fills with errors with a 72-byte memory leak. A small excerpt:
ERR005: Unable to open psglyphs data file!
ERR005: Unable to open character set file iso-8859-1!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open psglyphs data file!
ERR005: Unable to open character set file iso-8859-1!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open psglyphs data file!
ERR005: Unable to open character set file iso-8859-1!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
The above illustrates the reported hang mentioned in #349.

After applying #349 t6's 'volatile' fix to ps-pdf.cxx, no change.

Copy fonts and data to /usr/share/doc/htmldoc,
config/make all  <<<no hang>>>
cd doc && rm htmldoc.pdf
valgrind -v ../htmldoc/htmldoc --batch htmldoc.book -f htmldoc.pdf
Result: pdf created, with memory leak of 37 bytes

"configure --prefix=/usr" 'make' hangs looking for font width in /usr/share/htmldoc/fonts.

"make install DESTDIR=/tmp/htdoc"
cd doc && rm htmldoc.pdf
valgrind -v /tmp/htdoc/usr/local/bin/htmldoc --batch htmldoc.book -f htmldoc.pdf
Result: loop
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Bold.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Bold.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Times-Roman.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Helvetica-Oblique.afm!
ERR005: Unable to open font width file /usr/local/share/htmldoc/fonts/Helvetica-Oblique.afm!
...
This suggests the paths to data and fonts are not propagated to DESTDIR. 
Only using the supplied Makefile and doc/Makefile commands. I don't see "--datadir" in the Makefiles or Makedefs.
Makedefs line 46:   datadir = /usr/local/share
"configure --datadir=whatever" puts the fonts and data dirs somewhere else, but INSTALL.md says

Linux, macOS, and Other UNIX Platforms
--------------------------------------
To compile the software under UNIX you first need to run the "configure" script
in the source directory.  Usually this is just:
    ./configure
Then run "make" to build the software and generate the documentation:
    make
Finally, run "make install" (typically as root) to install the software:
    sudo make install

I just followed the above instructions and reported the results. If there are other instructions that would produce different results, please put them INSTALL.md. At least push the volatile fix to git.
It is NOT a compiler error. If you think it is, report it to https://gcc.gnu.org/bugzilla/

**Comment by michaelrsweet** [comment]
@hwpfeil The command you ran with Valgrind is missing the "--datadir .." option to HTMLDOC. Try running with that option.

The line in question is the same spot as issue #349.

**Comment by hwpfeil** [comment]
The command I ran is from doc/Makefile. That Makefile does not specify "--datadir". I merely added '-v' to the command as published. If "--datadir" is required, please change doc/Makefile to reflect that requirement.

**Comment by michaelrsweet** [comment]
From doc/Makefile:

```
HTMLDOC =       ../htmldoc/htmldoc$(EXEEXT) --datadir .. --strict
```

**Comment by hwpfeil** [comment]
Where is datadir defined? **Configure**. If not specified in the configure command, the default is PREFIX/share. Default PREFIX is /usr/local. Thus, "configure/make" causes doc/Makefile to invoke "htmldoc.pdf:" with datadir defined in Makedefs as /usr/share/htmldoc/fonts.

You missed my point: "make all" invokes doc/Makefile BEFORE "--datadir" exists. That is why make hangs looking for non-existing fonts and data dirs.

When I first reported that, I didn't search closed issues to find #343. That analysis addresses the first post in #349. That is why I suggesting moving the pdf and ps builds to the "make install" step.

**Comment by michaelrsweet** [comment]
@hwpfeil The default data directory is defined by the configure script. It is *overridden* using the `--datadir` option, which is part of the `HTMLDOC` variable defined in the documentation Makefile so that the documentation can be built from the source directory *without* requiring HTMLDOC to be installed first...

Again, the doc makefile uses `--datadir ..`, which tells HTMLDOC to look for the font and charset files in the base directory of the HTMLDOC sources and NOT in the installation directory, which as you correctly point out probably does not exist yet.

Verify that you do not have an environment variable called "HTMLDOC" defined - that will override the makefile variable of the same name and will cause the sort of problem you are seeing.

**Comment by hwpfeil** [comment]
The datadir race condition no longer exists in master. "git clone", configure, make does not hang looking for fonts and data directories. Thank you for fixing that.

**Comment by hwpfeil** [comment]
PS. It might be a smart idea to apply the volatile patch. Otherwise optimization might change 
while (col & 7); to while (true);
Example:
```
int main()
{
    int col = 0;
    
    do {
        col++;
    } while (col & 7);
   return 0; 
}
```
g++ -O3 -S test.cc
Results:  
main:
	"xorl	%eax, %eax"
	ret
Change "int col = 0;" to "volatile int col = 0;"
Results:
.L2:
	movl	-4(%rsp), %eax
	addl	$1, %eax
	movl	%eax, -4(%rsp)
	movl	-4(%rsp), %eax
	testb	$7, %al
The "volatile" hang results from col getting optimized away, leaving do{}while(true).

**Comment by michaelrsweet** [comment]
@hwpfeil First, the makefile hasn't changed in 2.5 years, and --datadir has been in there for far longer than that (long before HTMLDOC was hosted on Github...)

Second, "volatile" is in the process of being deprecated by the C and C++ standards committees. Adding it now will probably just guarantee that I have to remove it (or make its use conditional) in the future.

And finally, the purpose of volatile is to flag a variable that might change outside the local scope. Clearly that is NOT the case and the optimization that is being applied here is totally bogus. It is an obvious compiler bug that *has* been fixed in subsequent releases of the compiler. Short of refactoring this code (which I can look into, but *that* code hasn't changed since 2004...) I am not willing to make a change just to work around a compiler bug that is already fixed.
