### ISSUE TITLE
make fails with linking error

### ISSUE THREAD

**Issue by vestmon** [michaelrsweet/htmldoc#364]
In moving from CentOS 6 to CentOS 7, I am unable to rebuild htmldoc 1.9.5 because of an error.

Here is the output from make:

> Making all in htmldoc...
> Compiling gui.cxx...
> Compiling epub.cxx...
> Compiling html.cxx...
> Compiling htmldoc.cxx...
> Compiling htmlsep.cxx...
> Compiling license.cxx...
> Compiling markdown.cxx...
> Compiling mmd.c...
> Compiling ps-pdf.cxx...
> Compiling rc4.c...
> Compiling zipc.c...
> Compiling array.c...
> Compiling file.c...
> Compiling htmllib.cxx...
> Compiling http.c...
> Compiling http-addr.c...
> Compiling http-addrlist.c...
> Compiling http-support.c...
> Compiling image.cxx...
> Compiling iso8859.cxx...
> Compiling md5.c...
> Compiling progress.cxx...
> Compiling snprintf.c...
> Compiling string.c...
> Compiling tls.c...
> Compiling toc.cxx...
> Compiling util.cxx...
> Linking htmldoc...
> /bin/ld: gui.o: undefined reference to symbol '_ZN12Fl_File_Icon4findEPKci'
> //usr/lib64/libfltk.so.1.3: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[1]: *** [htmldoc] Error 1
> make: *** [all] Error 1
>

**Comment by michaelrsweet** [comment]
Did you re-run the configure script?

Is the FLTK library built for CentOS 7?

**Comment by vestmon** [comment]
Yes & yes.

**Comment by michaelrsweet** [comment]
"c++filt _ZN12Fl_File_Icon4findEPKci" reports this as `Fl_File_Icon::find(char const*, int)`, which should definitely be present in the FLTK library.

Did you build FLTK from source or are you using a pre-built library package?

**Comment by vestmon** [comment]
Pre-built.

**Comment by vestmon** [comment]
FIXED.  Added -lfltk to LIBS definition in Makedefs.

**Comment by michaelrsweet** [comment]
What is the output of "fltk-config --use-images --ldflags"?

**Comment by vestmon** [comment]
-lfltk_images

**Comment by michaelrsweet** [comment]
OK, it looks like the fltk package has a buggy fltk-config script - that command should return something like:

```
-lfltk_images -ljpeg -lpng -lz -lfltk
```

Please file a bug against the FLTK package in CentOS...
