### ISSUE TITLE
Any newer packaged versions available for Solaris 11?

### ISSUE THREAD

**Issue by ldesrosiers** [michaelrsweet/htmldoc#366]
The only packaged version for Solaris 11 we could find is 1.8.27 (https://www.opencsw.org/packages/htmldoc/).  We had been using 1.8.22 on Solaris 9, but that package is unavailable/incompatible.  It seems there was something changed between these versions, and possibly corrected in later version, that is causing some spacing issues for us (I believe it to be some font spacing).  Thanks.

**Comment by michaelrsweet** [comment]
Sorry, I'm not aware of any newer versions and I've not had Solaris-compatible hardware since 2007... If you have a compiler, you can build your own copy of HTMLDOC fairly easily.
