### ISSUE TITLE
--outfile ignored in CGI mode

### ISSUE THREAD

**Issue by vestmon** [michaelrsweet/htmldoc#367]
In ps-pdf.cxx the filename is hard-coded as "htmldoc.pdf" in CGI mode even if --outfile or -f is specified in a book file:

`
  if (CGIMode)
  {
    // In CGI mode, we only produce PDF output to stdout...
    printf("Content-Type: application/pdf\r\n"
	   "Content-Length: %ld\r\n"
	   "Content-Disposition: inline; filename=\"htmldoc.pdf\"\r\n"
	   "Accept-Ranges: none\r\n"
	   "X-Creator: HTMLDOC " SVERSION "\r\n"
	   "\r\n", ftell(out));
  }

`
Shouldn't the file name be used, if present?

**Comment by michaelrsweet** [comment]
Well, in CGI mode the output file is stdout; I can look at using the base name of the output filename, if any, rather than just "htmldoc.pdf"...

**Comment by vestmon** [comment]
The base name  would be better than the generic htmldoc.pdf but it wouldn't help here where I am using mod rewrite to map a request for www.mydomain.com/cal-2019-10.pdf to something like /cgi-bin/htmldoc/event_sub?src=calendar&yr=2019&mo=10.  Using the base name would still give all outfiles the same name,  equally useless to the user. There needs to be a method to specify the name dynamically.

**Comment by michaelrsweet** [comment]
@vestmon No, I mean the base name of the output file that is specified, not the base name of the incoming URL. We can't report a full URL or path since that isn't allowed in the Content-Disposition header for security reasons...

**Comment by vestmon** [comment]
I see. Ideally, an easier implementation for me would be to put it in a comment:



It could still default to htmldoc.pdf and would not require a book file.

**Comment by michaelrsweet** [comment]
@vestmon Hmm, that might be useful. But instead of a comment, a META tag is probably a better choice and we can use something like "HTMLDOC.filename" for the name, e.g.:

```
<meta name="HTMLDOC.filename" content="foobar.pdf">
```

**Comment by vestmon** [comment]
That was my first though, but the META tag name attribute value must be either 
application-name, author, description, generator, keywords or viewport according to the spec.

**Comment by michaelrsweet** [comment]
Actually, the [list of META tag names](https://wiki.whatwg.org/wiki/MetaExtensions) is much longer, and allows for extension...

**Comment by michaelrsweet** [comment]
[master d17eddd] Add support for HTMLDOC.filename META variable to control CGI mode filename (Issue #367)
