### ISSUE TITLE
Newlines ignored when rendering FOOTER in Linux systems

### ISSUE THREAD

**Issue by kovtunit** [michaelrsweet/htmldoc#368]
The same input html provides different PDFs when htmldoc is run under Windows and Linux systems.

Input: footer_issue.html
Output: footer_issue_win.pdf, footer_issue_rh.pdf

Executes from command line (respectively):

htmldoc.exe --quiet --webpage --charset koi8-r --embedfonts -t pdf footer_issue.txt >> footer_issue_win.pdf

htmldoc --quiet --webpage --charset koi8-r --embedfonts -t pdf footer_issue.txt >> footer_issue_rh.pdf

[footer_issue_win.pdf](https://github.com/michaelrsweet/htmldoc/files/3828647/footer_issue_win.pdf)

[footer_issue_rh.pdf](https://github.com/michaelrsweet/htmldoc/files/3828646/footer_issue_rh.pdf)

[footer_issue.txt](https://github.com/michaelrsweet/htmldoc/files/3828650/footer_issue.txt)

**Comment by michaelrsweet** [comment]
Multi-line footers are not supported.
