### ISSUE TITLE
An image put inline in a paragraph causes a premature page break.

### ISSUE THREAD

**Issue by mdykierek** [michaelrsweet/htmldoc#369]
For the attached example an inline image causes its caption appear on the subsequent page.
If the image is attributed with align="left" the issue goes away, so the code that handles inline images must break something with page increments.

[test.pdf](https://github.com/michaelrsweet/htmldoc/files/3846995/test.pdf)
![image](https://user-images.githubusercontent.com/27214784/68866387-9f24d700-06f4-11ea-8260-85ab4583dff0.png)

**Comment by mdykierek** [comment]
Testcase bash script and input files.
[testcase.zip](https://github.com/michaelrsweet/htmldoc/files/3847006/testcase.zip)

**Comment by michaelrsweet** [comment]
[master 77dc9b8] Fix an issue with page breaks with paragraphs using large inline images (Issue #369)

**Comment by michaelrsweet** [comment]
The code that advanced the line by the line height incorrectly looked for an additional line's worth of space at the bottom. It's a simple one-liner fix...

**Comment by mdykierek** [comment]
A minor note - on current master Windows build version still reads 1.9.7.

**Comment by michaelrsweet** [comment]
Thanks for noticing, I've updated the config.h files for both VisualStudio and Xcode now...
