### ISSUE TITLE
Support for Letterhead-Style Headers

### ISSUE THREAD

**Issue by ericschernoff** [michaelrsweet/htmldoc#372]
Hello,

In 1.8.27 and earlier, if you set a 650-700 pixel wide image as the logfile and set --header to .l., HTMLDoc would show that image full-size across the entire top of the page rather than just the middle 33%.  I think this was perceived as a bug by some, but it was extremely useful when preparing letters.  I have combed through the docs, but I haven't found a way to replicate the old behavior.

Is there an option to use a page-wide logo image as a header in the current version?  If not, please consider this for a future feature.

Thank you so much for creating this great utility.  I have relied on it for over 10 years, and it has been wonderful.

-Eric Chernoff

**Comment by michaelrsweet** [comment]
Hmm, maybe I can add support for an L format ("big logo") that fits the image across the width of the page?

**Comment by michaelrsweet** [comment]
[master 5e37ad3] Add letterhead header/footer image support (Issue #372)

**Comment by ericschernoff** [comment]
Michael,

Thank you so much for putting in this change so quickly!  This is perfect.

FYI, I have been using HTMLDoc with content written in the Summernote editor, and they make an awesome combination.  This software is indispensable.  Please let me know if there is a way to support this project.

Thank you,
-Eric
