### ISSUE TITLE
Header image overlaps text

### ISSUE THREAD

**Issue by ericschernoff** [michaelrsweet/htmldoc#373]
Hello,

This is a followup to issue #372.  The 'L' option does place the logo image all the way across the header, but the body content does get pushed down.  The body content overlaps the header unless you place a few <br> tags at the top of the HTML, which is only a good workaround for the first page.

I have experimented with setting a top-margin, but that moves down the header and the content.  Please advise if I am missing a key configuration option.

Thank you,
-Eric

**Comment by michaelrsweet** [comment]
No, the margin adjustment isn't accounting for the height of the letterhead image...

**Comment by michaelrsweet** [comment]
[master ed27364] Rework letterhead support as a separate image - the letterhead image is scaled differently than the logo/headerfooter images (Issue #373)
