### ISSUE TITLE
pkg-config is needed for https support on Debian 10

### ISSUE THREAD

**Issue by ptdev** [michaelrsweet/htmldoc#374]
Hello, I was just installing htmldoc from source on a new Debian 10 install and followed your install.md instructions including the required packages but the configure script wasn't detecting the ssl libraries until I also installed the pkg-config package.
I'm reporting this here as you might want to add it to the required packages list or be of help if somebody else is having the same issue.
Cheers, thanks for developing this.

**Comment by michaelrsweet** [comment]
No worries, I'll add it to the list of required packages.
