### ISSUE TITLE
Letterhead option still does not push down the bodytext

### ISSUE THREAD

**Issue by ericschernoff** [michaelrsweet/htmldoc#375]
Hi Michael,

I am very sorry to be a pest, but the letterhead option is still not pushing down the content as expected.  I have attached the output that I am receiving for this command:

 /usr/local/bin/htmldoc -t pdf content.html --webpage --letterhead 1581284393_19DE267F234326531A6D.png  --header .L. > letter.pdf

I have also attached the PNG file and the content used to make that letter.  ( had to that as a .txt file for some reason.)  Please advise if I am doing something wrong.

Also, FYI, I have revived the Perl module to work with HTMLDOC:  https://metacpan.org/pod/HTML::HTMLDoc

Thank you very much.

[content.txt](https://github.com/michaelrsweet/htmldoc/files/4207727/content.txt)

[letter.pdf](https://github.com/michaelrsweet/htmldoc/files/4207725/letter.pdf)

![1581284393_19DE267F234326531A6D](https://user-images.githubusercontent.com/27785966/74581386-f6994400-4f7c-11ea-839d-b2e6b1f507b9.png)

**Comment by michaelrsweet** [comment]
No worries, looks like I forgot to add the letterhead height to the margins in all places. (Guess I should have tested with a taller image...)

**Comment by michaelrsweet** [comment]
[master 9bbb4ec] Fix top/bottom margins with taller letterhead images (Issue #375)
