### ISSUE TITLE
create empty file

### ISSUE THREAD

**Issue by Pratiktarade** [michaelrsweet/htmldoc#376]
Hi Team please check bellow code
#######################################
my $htmll = new HTML::HTMLDoc();

$htmll->set_page_size('letter'); # set page size
$htmll->set_bodyfont('Arial'); # set font
$htmll->set_fontsize(8.0); # set fontsize
$html->set_permissions('none');

print Dumper $htmll->set_html_content(qq{Hello World });
$htmll->title();
$htmll->set_header('.', 't', '.');
$htmll->set_footer('D', '.', '/');

print Dumper my $pdf = $htmll->generate_pdf(); # generate document

$pdf->to_file("$BASEPATH/macro/$proj/Files/pratik.pdf");

print $htmll->get_html_content();

######### ######################
ERROR

$VAR1 = 1; $VAR1 = bless( { 'content' => \undef }, 'HTML::HTMLDoc::PDF' ); Hello World

**Comment by michaelrsweet** [comment]
Sorry, I don't actually support this module, just the core program using it.
