### ISSUE TITLE
https web pages not readable in windows machine

### ISSUE THREAD

**Issue by alexgoa** [michaelrsweet/htmldoc#378]
Hello,
I've installed the version 1.9.6 and 1.9.8 on a windows server 2019 machine 
When I try to create a pdf from whatever https, it gives me the error
Unable to open https;//….. for reading.
What can I do to fix this issue?
Thanks 
Alex

**Comment by michaelrsweet** [comment]
@alexgoa How did you install them?

Any errors showing up in the event log?

**Comment by alexgoa** [comment]
Hello, I've installed on using the msi file provided (htmldoc-1.9.8-windows.msi).
No errors showing

**Comment by michaelrsweet** [comment]
@alexgoa This could be an issue with Windows Server - HTMLDOC uses the Windows SSPI layer, so it might be preventing HTMLDOC from negotiating a secure connection.

**Comment by alexgoa** [comment]
hello. I've also try to use htmldoc with https://www.google.it and there's the same error
I'm using my htmldoc from my windows 10 laptop

**Comment by alexgoa** [comment]
Hello
I've had the same error using the htmldoc Gui to create a pdf file and trying to get the https://www.google.com page
Similar error 
Unable to connect to ...
Unable to open "https..."
No input files to fromat. cannot generate the document.
My pc is win 10 home 64 bit
htmldoc version 1.9.3
I don't know if this helps but if I put http instead - although Google is sistematically redirecting http requests to https - the htmldoc work is done perfectly.

**Comment by michaelrsweet** [comment]
@alexgoa Sorry I've been busy with another project but will try to reproduce this over the weekend.

**Comment by alexgoa** [comment]
I would like just to thank you for your work. 
I run a small consultants company and your component has been very helpful.
Thanks for your work and efforts.
Alex

**Comment by michaelrsweet** [comment]
OK, I've managed to reproduce it in a Windows Server VM. Investigating...

**Comment by alexgoa** [comment]
thanks a lot.
Alex

**Comment by michaelrsweet** [comment]
OK, I have a fix:

[master cd5d874] Fix Windows TLS support - client-side needs to use empty credentials.

[master 4673a06] Clean up - make_credentials will always have a common_name (server), client always gets anonymous creds with find_credentials.
