### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by alexgoa** [michaelrsweet/htmldoc#380]
Good morning,
I've a question to which I can't find anser in the htmldoc manual.
I've a html page with a certificate image in the background and, on the front, some text like company name and other texts. 
I can't find how to use the background image in htmldoc (version 1.9.6) generating pdf.
The only solution I've found is to split in many tiles the image with photoshop and upload it as a html page with a table containing the tiles. This create also the space for the above texts. 
Is there anybody who can give me a suggestion ?
Thanks 
Alessandro

**Comment by michaelrsweet** [comment]
@alexgoa Right now the only thing you can do is pass the `--bodyimage filename.ext` option or set the background on the body, e.g.:

```
<body background="filename.ext">
```

The image itself has to be sized based on the page size and browser (pixel) width setting, which defaults to 680 for historical reasons (works out to be 80 pixels per inch for US Letter).

**Comment by alexgoa** [comment]
Thanks Michael
