### ISSUE TITLE
Combining Files Located in Branches of a Base Folder

### ISSUE THREAD

**Issue by aholden10** [michaelrsweet/htmldoc#381]
Hello - If these folders all start in /home/user/ then branch into a tree something like this:
basefolder
      index.html
folder1
      index.html 
      file1.html
      file2.html
folder2
      index.html 
      file1.html
      file2.html

I thought this command would assemble all seven of the html files in the three subfolders into a single output PDF:

htmldoc --webpage --path /home/user/ -f output.pdf *.html

But it doesn't...any thoughts about what I am doing wrong?

I'd be happy to write it up in the docs to help future users.

**Comment by michaelrsweet** [comment]
HTMLDOC doesn't recursively look for files matching the wildcards - that is normally handled by the shell you use, and on Windows by the C runtime, and neither recurses.

What you want is to add "*/*.html" to the command-line.

**Comment by aholden10** [comment]
Michael - thank you, I very much appreciate your quick reply!
    On Monday, March 30, 2020, 05:50:13 PM EDT, Michael R Sweet <notifications@github.com> wrote:  
 
 


HTMLDOC doesn't recursively look for files matching the wildcards - that is normally handled by the shell you use, and on Windows by the C runtime, and neither recurses.

What you want is to add "/.html" to the command-line.
