### ISSUE TITLE
ERR005: Unable to read HTMLDOC installation from registry

### ISSUE THREAD

**Issue by muv1** [michaelrsweet/htmldoc#382]
If you extract the installer like this:

~~~
lessmsi x htmldoc-1.9.8-windows.msi
~~~

then try to run:

~~~
APPDIR/htmldoc a.html
~~~

You get this result:

~~~
ERR005: Unable to read HTMLDOC installation from registry!
ERR005: Unable to open psglyphs data file!
ERR005: Unable to open character set file iso-8859-1!
ERR005: Unable to open font width file
   C:/Program Files/HTMLDOC/fonts/Helvetica-Bold.afm!
~~~

The font paths should be coded as relative to the executable, rather than
absolute. For example something like this:

~~~
fonts/Helvetica-Bold.afm
~~~

**Comment by muv1** [comment]
Workaround, create a file `a.reg` similar to this:

~~~reg
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\Software\HTMLDOC]
"data"="C:\\APPDIR"
~~~

**Comment by michaelrsweet** [comment]
The canonical way of doing this on Windows is to use the registry, which is why I do so and document it in the users manual and INSTALL.md file...
