### ISSUE TITLE
Support for custom fonts

### ISSUE THREAD

**Issue by mbo77** [michaelrsweet/htmldoc#384]
I've been searching, but was unable to find an answer. If so, the ticket can be closed.
Would it be possible to add support for custom fonts?
I'd like to embed and use other fonts than those available.

**Comment by michaelrsweet** [comment]
@mbo77 Sorry, right now HTMLDOC's font support is extremely limited. I'm hoping to change that at some point in the future, but doing so requires some massive changes to how HTMLDOC works...
