### ISSUE TITLE
Support "monospace" as well as "mono" for FONT element

### ISSUE THREAD

**Issue by vestmon** [michaelrsweet/htmldoc#385]
In CGI, I am attempting to display <font face="monospace"> and getting the default proportional font.  <font face="courier"> works, but I was trying to use DejaVu Sans Mono. Is there a workaround for this?

**Comment by michaelrsweet** [comment]
@vestmon How are you selecting the font?

**Comment by vestmon** [comment]
I have tried the FONT tag, a TT tag, and the CODE tag. I don't need it for
the entire document only a section.

**Comment by vestmon** [comment]
I realize the edit stripped the tags from my original post: `<font  face="monospace">`

**Comment by vestmon** [comment]
I also noted that `<font face="courier">` works.

**Comment by michaelrsweet** [comment]
Right now the code is just looking for/supporting `<font face="mono">`. I can add "monospace" as an alternate name...

**Comment by michaelrsweet** [comment]
[master 35cba49] Add support for `<FONT FACE="monospace">` (Issue #385)
