### ISSUE TITLE
Can't find libpng16.16.dylib in MacOS Catalina

### ISSUE THREAD

**Issue by daveyboond** [michaelrsweet/htmldoc#386]
Hi Michael,

I have not been able to run HTMLDOC on my MacOS Catalina because /usr/local/opt/libpng/lib/libpng16.16.dylib does not exist. I tried setting up a symlink to a copy of libpng16.16.dylib I have elsewhere, but it wouldn't give me permission to use it.

Steve

**Comment by michaelrsweet** [comment]
This is a packaging issue; for some reason it picked up an old dylib from Brew that was left on my system. I will post an updated binary in the near future...
