### ISSUE TITLE
htmldoc with cloudflare

### ISSUE THREAD

**Issue by PeteW4W** [michaelrsweet/htmldoc#387]
Hi,
we use htmldoc for many years. Thank you.
Recently we use cloudflare at our server and since then htmldoc has stopped working. We get always the message "ERROR: No HTML files!" as if the file could not be found. But the file exists.
If we deactivate cloudflare, htmldoc will work again immediately without any changes.
The support of cloudflare cannot find a problem. The Server IP is not blocked.
What problem can that be?
What else can we test?

Thank you.
Pete

**Comment by michaelrsweet** [comment]
@PeteW4W I've never used cloudflare so I have no clue what the issue might be. Are you running HTMLDOC on the server or ???

What operating system?

What version of HTMLDOC?

**Comment by PeteW4W** [comment]
Yes its running on the server.
Its a Apache/2.4.41 
We use htmldoc 1.8.27 but we tested also the newest version with the same result.

**Comment by michaelrsweet** [comment]
@PeteW4W What operating system?

**Comment by PeteW4W** [comment]
Linux
