### ISSUE TITLE
[question] is possible to provide the HTML input as a string?

### ISSUE THREAD

**Issue by DenisMirandaJ** [michaelrsweet/htmldoc#389]
What I mean is, instead of doing this

> htmldoc --webpage -f output.pdf filename.html

do something like this

> htmldoc --webpage -f output.pdf "valid html string here"

Thanks in advance

**Comment by michaelrsweet** [comment]
@DenisMirandaJ Not at present, although you *can* provide it on the standard input, e.g.:

    echo "valid html string" | htmldoc --webpage -f output.pdf -
