### ISSUE TITLE
version 1.9.9 crashes on windows 10 machine

### ISSUE THREAD

**Issue by alexgoa** [michaelrsweet/htmldoc#390]
Hello Michael,
I've installed the 1.9.9 version on a brand new win 10 machine updated with all microsoft updates
I've downloaded the .msi version
When I try to 
- compile the pdf for http or https://www.google.it or from a local html page
- save a book file for later use
it crashes and disappear from the screen without any further notice.
No messages on the screen. 
No work is done.
thanks as usual for your work
Alex

**Comment by michaelrsweet** [comment]
Strange, I'll try testing this on my "throwaway" Windows laptop. I seemed to work just fine in my usual testing VMs.

**Comment by michaelrsweet** [comment]
OK, so on my Windows laptop I see the package is missing the vc140 runtime DLL... Which the installer is supposed to embed...  Hang on while I work on building an updated package...

**Comment by michaelrsweet** [comment]
@alexgoa I've uploaded a new MSI for Windows that includes the MSVC runtime merge module. Strange that it only affected the HTMLDOC GUI program (ghtmldoc.exe) but not the command-line program (htmldoc.exe)...

**Comment by alexgoa** [comment]
Hello, with the new htmldoc releases I see this error "libpng warning:
iCCP: known incorrect sRGB profile" and when this happen the whole html
page is not included in the pdf.
What does the error mean?
what could cause it?
In the html page there are tables, texts and some icons which have worked
fine until the previous version (1.8.4).

thanks
Alessandro

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mer 17 giu 2020 alle ore 20:55 Michael R Sweet <
notifications@github.com> ha scritto:

**Comment by michaelrsweet** [comment]
@alexgoa Please open a new Github issue and attach a sample HTML and PNG file demonstrating this issue.

**Comment by michaelrsweet** [comment]
And FWIW, this libpng warning business appears to be a fairly common issue for PNG files created with older versions of Adobe apps...
