### ISSUE TITLE
Segmentation error (core dumped) with version 1.9.8 and more

### ISSUE THREAD

**Issue by broadcastyourseb** [michaelrsweet/htmldoc#391]
I'm using Linux Mint 19.3 Cinnamon with version 1.9.2 by default.
I tried to compiled version 1.9.9 which ended with a core dump when I tried to save a book file as. Same thing with the snap image 1.9.9.
I encountered the same issue with version 1.9.8
Version 1.9.7 works fine.

Here comes the result of the command ./confire and make with version 1.9.8
[configure.txt](https://github.com/michaelrsweet/htmldoc/files/4840122/configure.txt)
[make.txt](https://github.com/michaelrsweet/htmldoc/files/4840123/make.txt)

**Comment by michaelrsweet** [comment]
OK, I've been able to reproduce.

**Comment by michaelrsweet** [comment]
[master 20f362c] Fix GUI crash bug (Issue #391)
