### ISSUE TITLE
Setting the footer for the first page

### ISSUE THREAD

**Issue by ericschernoff** [michaelrsweet/htmldoc#392]
Hello,

I hope you are doing well.  I am writing because I use the FOOTER LEFT and FOOTER RIGHT comments in my generated HTML, and we really need those comments to take effect for the first page of the PDF.  

Unfortunately, it seems those comments only work on the "next page", which precludes the very first page.  Please let me know if I have missed an option, or if this is possible to include in an upcoming release.

Thank you very much!

-Eric Chernoff

**Comment by birdwes** [comment]
Try using --header and --footer command line options for the first page?

**Comment by ericschernoff** [comment]
Thanks birdwes,

That works great -- thank you!

-Eric
