### ISSUE TITLE
Markdown input gives "ERR002: Error: no pages generated!"

### ISSUE THREAD

**Issue by abitrolly** [michaelrsweet/htmldoc#393]
Trying to convert .txt or .md file from command line using snap fails.
```
$ htmldoc -f anatoli.cv.pdf anatoli.cv.txt
ERR002: Error: no pages generated! (did you remember to use webpage mode?
```
[anatoli.cv.txt](https://github.com/michaelrsweet/htmldoc/files/4928157/anatoli.cv.txt)

**Comment by michaelrsweet** [comment]
Use the `--webpage` option.

**Comment by abitrolly** [comment]
But I need PDF. Why webpage?

**Comment by michaelrsweet** [comment]
"--webpage" tells HTMLDOC that you are just converting a web page/simple document with no headings. This is explained in the HTMLDOC user's manual.

**Comment by abitrolly** [comment]
But I am converting plain text.
