### ISSUE TITLE
Can't issue <!-- PAGE BREAK --> inside a <PRE>

### ISSUE THREAD

**Issue by erco77** [michaelrsweet/htmldoc#394]
Seems `<!-- PAGE BREAK -->` is ignored if inside a large `<PRE>`.

**Comment by erco77** [comment]
Example code `foo.html`:
```
<HTML>
<PRE>
line one
line two
<!-- PAGE BREAK -->
line three
line four
</PRE>
</HTML>
```
..when run through: `htmldoc --webpage foo.html -f foo.pdf` results in the unexpected single page.
Removing `<PRE>/</PRE>` causes the expected two pages.

**Comment by michaelrsweet** [comment]
[master b42ee1f] Support page comments inside pre text (Issue #394)
