### ISSUE TITLE
Webpage URL truncated after redirect

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [michaelrsweet/htmldoc#396]
I observed the following problem with **HTMLDOC 1.9.10**

I do the following call from command line:
`c:/htmldoc/htmldoc --embedfonts --compression=9 --left 1cm --top 1cm --bottom 1cm --headfootsize 7 --format pdf14 --header t.. --footer D./  --webpage "http://localhost/simon/modules/max/reports/generaldata.php?pat_id=173&beg_date=Aug+22+2012+12:56PM&end_date=Sep++9+2020+12:31PM&beg_date_p=Aug+22+2012+12:56PM&end_date_p=Sep++9+2020+12:31PM&rtm=0&room=141&title=Stammdaten&logpath=D%3A%5CApps%5CApache%5Csimon%5Cmodules%2Fmax%2Flog_oscar%2F&mode=oscar&documentID=9999_0000000964_0000000001&showuserlist=1" -f "D:\Apps\Apache\simon\modules/max/exchange_oscar/\TMP1_XXX_CCU_115$51155b_test_Blood-Products_abc_115$51155c_Stammdaten_964_16_0000000001.pdf"`

My webserver (apache) redirects the http request to https. The access.log has this two lines:
`127.0.0.1 - - [10/Sep/2020:08:18:40 +0200] "GET /simon/modules/max/reports/generaldata.php?pat_id=173&beg_date=Aug+22+2012+12:56PM&end_date=Sep+9+2020+12:31PM&beg_date_p=Aug+22+2012+12:56PM&end_date_p=Sep+9+2020+12:31PM&rtm=0&room=141&title=Stammdaten&logpath=D:\\Apps\\Apache\\simon\\modules/max/log_oscar/&mode=oscar&documentID=9999_0000000964_0000000001&showuserlist=1 HTTP/1.1" 301 588`
`127.0.0.1 - - [10/Sep/2020:08:18:40 +0200] "GET /simon/modules/max/reports/generaldata.php?pat_id=173&beg_date=Aug+22+2012+12:56PM&end_date=Sep+9+2020+12:31PM&beg_date_p=Aug+22+2012+12:56PM&end_date_p=Sep+9+2020+12:31PM&rtm=0&room=141&title=Stammdaten&logpath=D:\\Apps\\Apache\\simon\\modul HTTP/1.1" 200 62`

Please note:
**The second line is truncated**, because of that the PHP Script on the Webserver will fail with an error, the error message will be written into the PDF.

**Comment by michaelrsweet** [comment]
The current HTTP client code supports a maximum redirect URL length of 255 characters (side effect of the CUPS code I'm using), which causes the URL to be truncated.

I should be able to update the HTTP code to the latest CUPS 2.3.x bits which remove the 255 character limit.

**Comment by michaelrsweet** [comment]
[master 41cca81] Update the embedded (CUPS) HTTP library to the latest version to fix the truncated redirection URL problem (Issue #396)
[master 3757b86] Fix build error on Windows (Issue #396)
[master 49dfe28] Fix compile issues on Linux (Issue #396)
