### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [michaelrsweet/htmldoc#398]
I were using the htmldoc version 1.8.23 for quite some years now.

I wanted to support HTTPS with my application and tried to use htmldoc 1.9.10 as a drop in replacement, but there are performance issues.

The newer version is very slow - compared to the old one it needs around 7 times longer for the same amount of reports. 
It is a loop calling htmldoc.exe for about 100 URLs on my webserver, the scripts on the webserver are fast, the resulting html is short (will fit easy on one pdf page) and simple. Old version needed 2 minutes, the new version will always take 13 minutes - even when HTTPS is not active.

I read this ticket:
https://github.com/michaelrsweet/htmldoc/issues/345
and there you are positive that 1.9 should be as fast as 1.8. You were discussion bitness though.
**Does the 1.9.10 MSI package install the 64 bit Version?**

I was also thinking about the other 1.8 versions, but reading the changelog I was confused: 
**Is there an 1.8.x version that will support HTTPS?**

**Comment by OwnerOfThisIsle** [comment]
I just did a test run with the 1.8.30 (MSI) and deactivated HTTPS and interestingly it is also quite slow - it took about 11 minutes.

**Comment by michaelrsweet** [comment]
@OwnerOfThisIsle Since 1.8.23 is so old (released October 2002), it will be hard to tell what specifically is causing this slowdown. One change that happened since that version is that HTMLDOC now, by default, embeds the fonts it uses. You can try using the `--no-embedfonts` option to see if that eliminates the extra time spent.

**Comment by OwnerOfThisIsle** [comment]
Thx I will try that and post the results. 
Can you explicitely answer the questions in bold?

**Comment by OwnerOfThisIsle** [comment]
I did the --no-embedfonts test:
When I was using 1.8.23 I always explicitely called --embedfonts.
So I was not expecting performance improvements, but strange:

When I use 1.9.10 with the explicit --no-embedfonts option it took about 4 minutes, which is still slower than 1.8.23, but much faster than with the embedded fonts.

However this might not be a solution for me, since the --embedfonts option, will be needed as f.i. it is one of the requirements for PDF/A.

**Comment by michaelrsweet** [comment]
@OwnerOfThisIsle The 1.9.x MSI packages are 64-bit. The old 1.8.x packages were 32-bit.

All of the 1.8.x releases supported HTTPS, but changes to the Microsoft-supplies TLS stack over the last year or more (which were backported to older versions of Windows) broke the HTMLDOC HTTPS support - that was just fixed in the most recent HTMLDOC update.

I honestly don't know what the extra run time could be attributed to as I've purposefully limited the changes to the HTMLDOC source code as much as possible. I *did* add the Deja-Vu fonts back in 1.8.25, so maybe those are getting used in your documents? They are bigger than than old Times/Helvetica/Courier base fonts. It is also possible that the MS runtime is just slower - there are a number of security "enhancements" that could be causing a slowdown, although I wouldn't expect it to be so severe...

**Comment by slobo** [comment]
This might be just noise for the purpose of this discussion, on Linux, (no)-embedfonts doesn't seem to make any significant difference in performance on a larger file.

But I found with 1.9.2 (that comes with Ubuntu 18.04) using `--charset utf-8` on a ~90KB html file it took 4 times as long as with `iso-8859-1`. (UTF-8 took 14 s vs 3s for Latin 1)

1.9.10 (from snap) is much faster with both charsets - less than 1 second on the same machine.

**Comment by OwnerOfThisIsle** [comment]
@michaelrsweet: Thank you for your answers. 
I did more tests, I wanted to remove my serverside php scripts from the game, so I created a simple html file.

First I put this on my apache webserver and called 10x:
`c:/htmldoc/htmldoc --embedfonts --compression=9 --left 1cm --top 1cm --bottom 1cm --headfootsize 7 --format pdf14 --header t.. --footer D./  --webpage "http://localhost/simon/test.html" -f "D:\Apps\Apache\simon\test\1.pdf"`
this took about **24 s**.

Then I wanted to bypass the webserver and called 10x:
`c:/htmldoc/htmldoc --embedfonts --compression=9 --left 1cm --top 1cm --bottom 1cm --headfootsize 7 --format pdf14 --header t.. --footer D./  --webpage "D:\Apps\Apache\simon\test.html" -f "D:\Apps\Apache\simon\test\1.pdf"`
this took about **2 s**.

Doing the same with my 1.8.21 version, I had 5-6 s for using the webserver and 3 s when bypassing it.

@slobo :
I checked charsets: Apache is configured to deliver `iso-8859-1`, all files are stored in the same charset.



**Conclusion:**
**For the most part htmldoc 1.9.10 IS faster, than the older version, but not when using the http(s) protocol for the source.**
Could it be that a proxy slows everything down, while an older version of htmldoc is just ignoring it?
Or is the older version in a way security unaware that it soo fast with http?
Other ideas?

**Comment by OwnerOfThisIsle** [comment]
Using my test env from above, I also retested the `--no-embedfont` Option:
When using http it will take 23-24 s nearly as before. 
Resulting pdfs were smaller, so it seems to work, but no relevant time difference.  I must have made a mistake in my measurements last week, Sorry!

**Comment by OwnerOfThisIsle** [comment]
Problem solved!

For further tests I installed a clean new apache on my system.
My measurements with the new apache were much better, so I started to compare configurations and finally found the culprit in the Listen Directive in my vhost.conf:
`Listen 0.0.0.0:80` is slow.
`Listen 80` is fast.

This setting is not a problem when I use web browsers like chrome, and HTMLDOC 1.8.21 seem to handle it as well, but the current version needs 2 additonal seconds for each call..
Thx for your patience with me and my edge case.

**Comment by michaelrsweet** [comment]
OK, to close the loop on this, the newer HTTP code in later versions of HTMLDOC supports IPv6 and tries connecting on every address that comes back from the host lookup. By using "Listen 80" you are listening on both IPv4 (0.0.0.0) and IPv6 (::) so it'll get a faster response...
