### ISSUE TITLE
Relative path to image not working

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [michaelrsweet/htmldoc#400]
I have the following HTML on my apache as source for HTMLDOC:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<body style='margin:0px; padding: 0px;'>
<img alt="header_GE.gif" height="114" src="../config/images/header_GE.gif" width="650">
</body>
</html>
```
The picture is in the the directory, it opens when I load the HTML in a browser.
Apache Log:
```
127.0.0.1 - - [22/Sep/2020:11:49:04 +0200] "GET /simon/test/test.html HTTP/1.1" 200 223
127.0.0.1 - - [22/Sep/2020:11:49:04 +0200] "GET /simon/config/images/header_GE.gif HTTP/1.1" 304 -
```

If I call HTMLDOC to print that pic in a pdf:
`c:/htmldoc/htmldoc --embedfonts --compression=9 --left 1cm --top 1cm --bottom 1cm --headfootsize 7 --format pdf14 --header t.. --footer D./  --webpage "https://localhost/simon/test/test.html" -f "D:\Apps\Apache\simon\test\1.pdf"`
this will fail:

> ERR403: Forbidden (https://localhost:443/config/images/header_GE.gif)
> PAGES: 1
> BYTES: 38817

Apache Log in that case:
```
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /simon/test/test.html HTTP/1.1" 200 259
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /config/images/header_GE.gif HTTP/1.1" 403 199
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /config/images/header_GE.gif HTTP/1.1" 403 199
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /config/images/header_GE.gif HTTP/1.1" 403 199
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /config/images/header_GE.gif HTTP/1.1" 403 199
::1 - - [22/Sep/2020:11:49:11 +0200] "GET /config/images/header_GE.gif HTTP/1.1" 403 199
```

**Comment by OwnerOfThisIsle** [comment]
Relative links with leading slashes like this:
```
<img alt="header_GE.gif" height="114" src="/simon/config/images/header_GE.gif" width="650">
```
would work as expected.

**Comment by OwnerOfThisIsle** [comment]
But links without leading slashes like this:
`<img src="config/images/header_GE2.gif">`
would search for the image in 
`http://localhost:80/simon/config/images/header_GE2.gif`
while expected behaviour would be to seach for the image in the path relative to the html file (which is in the directory test)
`http://localhost:80/simon/test/config/images/header_GE2.gif`

**Comment by OwnerOfThisIsle** [comment]
Accidently closed.

**Comment by LuxSum** [comment]
I can confirm this is an issue as I have had to rewrite a whole bunch of paths to make sure they are from the root directory.

**Comment by michaelrsweet** [comment]
@OwnerOfThisIsle Do you have a public URL you can send me that exhibits this issue? I've tried a couple of my sites and haven't been able to reproduce...

**Comment by michaelrsweet** [comment]
@OwnerOfThisIsle Closing for now. Please provide the requested information and I'll re-open to investigate...
