### ISSUE TITLE
htmldoc usage with snap

### ISSUE THREAD

**Issue by peterdutton** [michaelrsweet/htmldoc#402]
Hi,

We are moving to a new OS version (CentOS 8), and this is our first time using HTMLDOC from the snap package; previously we used it via the main CentOS repo.

My question is to do with the temporary folders. It seems that the snap packaging isolates HTMLDOC so that it uses its own `tmp` directory; in my case this is `/tmp/snap.htmldoc/tmp/`.

This causes a problem because I generate a HTML file to another `tmp` directory (in PHP) but HTMLDOC cannot access it.

Do you know of a way round this? I have solved similar issues with systemd sharing a temporary folder but I can't see how I would apply that to a package within snap.

Thanks for your help!

**Comment by michaelrsweet** [comment]
@peterdutton Hmm, I thought I had provisioned it for this use case, but I guess maybe not? Will investigate what needs to be done!

**Comment by peterdutton** [comment]
Many thanks @michaelrsweet . Alternatively if there's any way to supply the HTML 'inline' rather than as a file - or to pipe it in - that may help to get around it.

**Comment by michaelrsweet** [comment]
@peterdutton You can specify "-" as an input filename to read the HTML from stdin.  And "-f -" will send the output to stdout.

**Comment by peterdutton** [comment]
Thanks @michaelrsweet  - I'll give that a try.

**Comment by peterdutton** [comment]
Hi @michaelrsweet - I've been attempting to get this running, but still seem to have permissions issues within the snap installation. I don't think the application is initialising properly when it's run from php. The `exec` command is running as the 'apache' user, and when I look at the error output from any HTMLDOC command I get the following error:

```
cmd_run.go:918: WARNING: cannot create user data directory: cannot create "/usr/share/httpd/snap/htmldoc/467": mkdir /usr/share/httpd/snap: permission denied
Sorry, home directories outside of /home are not currently supported.
See https://forum.snapcraft.io/t/11209 for details.
```

Should I try to run as a different user? Looking at the output of `echo ~` for the apache user, the home directory is /usr/share/httpd.

**Comment by michaelrsweet** [comment]
@peterdutton I'm thinking you need to connect the system-files interface to HTMLDOC with:

    snap connect htmldoc:system-files :system-files

but that doesn't seem to work with the current snap... I'll push an update shortly that you can test.

**Comment by michaelrsweet** [comment]
@peterdutton OK, so I'm in the process of getting a "manual review" since (I guess) the system-files interface requires explicit approval. The new interface will be called "htmldoc:config-ro-system" to provide read-only access to the root filesystem.

Unfortunately, there doesn't appear to be a way to override a snap's directory configurations - it would be nice to offer a way to open up a specific (set) of directories rather than the whole root filesystem...

**Comment by peterdutton** [comment]
Great - thanks for the update @michaelrsweet  :+1: 

Yes, I read into the snap issues a bit before posting back this week; it seems like the structure is fixed and they don't have plans to change it!

**Comment by michaelrsweet** [comment]
@peterdutton So I've tried adding read-only access to the root filesystem, and apparently they won't allow that for snaps unless there is a clear and "compelling" reason, and I don't think I'm going to be able to convince them that HTMLDOC needs root filesystem access... :/

So I guess the best solution for now is to use the CentOS package or compile from source...

**Comment by peterdutton** [comment]
@michaelrsweet Thanks for letting me know. On CentOS 8 there is no package for HTMLDOC, which is the reason why I tried to use the snap. I'll have a look at building from source instead.
