### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/htmldoc#406]
I would like to point out that identifiers like “[`_HTMLDOC_CXX_`](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/htmldoc.h#L116 "Update candidate")” and “[`_PROGRESS_H_`](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/progress.h#L12 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by michaelrsweet** [comment]
As these identifiers have been used in HTMLDOC for 26 years without incident, I'm not going to bother with a gratuitous change for the sake of conformance to a language standard that changed underneath me.

**Comment by elfring** [comment]
:crystal_ball: I hope that [undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?") can eventually be avoided also for this software.
