### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/htmldoc#407]
Would you like to add more error handling for return values from functions like the following?
- [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [image_copy](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/image.cxx#L571)
- [fputs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.") ⇒ [write_footer](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/htmlsep.cxx#L338)
- [strdup](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [get_format](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/util.cxx#L254)

**Comment by michaelrsweet** [comment]
@elfring I don't need more bug hunting quests. Please provide specific issues and not "this and a lot more like it" reports.

**Comment by elfring** [comment]
What do you find not specific enough according to the information that [some return values are ignored](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") so far?

:thinking: There are some solution approaches possible for this purpose.
