### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [michaelrsweet/htmldoc#408]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [get_format](https://github.com/michaelrsweet/htmldoc/blob/f16285c92c5aa12fd4aaac72c9417fd09ad603dc/htmldoc/util.cxx#L245 "get_format function")
- [httpClearCookie](https://github.com/michaelrsweet/htmldoc/blob/41cca81f5cfbd507fe4f43c7c6a3c6c72e16e50a/htmldoc/http.c#L276 "httpClearCookie function")

**Comment by michaelrsweet** [comment]
Closing this out for now; I'll modernize the usage here as the code is touched for other fixes or when I replace it with newer code.
