### ISSUE TITLE
htmldoc Compilation for ARM through yocto is not successfull

### ISSUE THREAD

**Issue by tany5522** [michaelrsweet/htmldoc#420]
Hi ,
I am trying to integrate HTMLDOC package to yocto build system.
I am using the "inherit autotools" to configure and compile.
I generated the configure.ac  from yocto and started to compile.
But ended up seeing many issues specially in png/pngrtran.c.
Please find the error:

_>  Compiling testhtml.cxx...
> | Linking testhtml...
> | /home/apurna/project-space/fsp/phase2/platform-fsp-manifests/build-am335x-evm-test/tmp/work/armv7at2hf-neon-poky-linux-gnueabi/htmldoc/1.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/8.3.0/ld: ../png/libpng.a(pngrtran.o): in function `png_do_read_transformations':
> | /usr/src/debug/htmldoc/1.0-r0/png/pngrtran.c:4782: undefined reference to `png_riffle_palette_neon'
> | /home/apurna/project-space/fsp/phase2/platform-fsp-manifests/build-am335x-evm-test/tmp/work/armv7at2hf-neon-poky-linux-gnueabi/htmldoc/1.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/8.3.0/ld: ../png/libpng.a(pngrtran.o): in function `png_do_expand_palette':
> | /usr/src/debug/htmldoc/1.0-r0/png/pngrtran.c:4323: undefined reference to `png_do_expand_palette_rgba8_neon'
> | /home/apurna/project-space/fsp/phase2/platform-fsp-manifests/build-am335x-evm-test/tmp/work/armv7at2hf-neon-poky-linux-gnueabi/htmldoc/1.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/../../libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/8.3.0/ld: /usr/src/debug/htmldoc/1.0-r0/png/pngrtran.c:4354: undefined reference to `png_do_expand_palette_rgb8_neon'
> | collect2: error: ld returned 1 exit status
> | Makefile:125: recipe for target 'testhtml' failed

The function implementations are missing in the code.

Could you please help me with the compilation for ARM7 processor

[Makefile.zip](https://github.com/michaelrsweet/htmldoc/files/5993858/Makefile.zip)

**Comment by michaelrsweet** [comment]
@tany5522 Add a DEPENDS line to your recipe, e.g.:

    DEPENDS = "libjpeg-turbo libpng zlib"

That will get the Yocto build to use the standard image libraries instead of the built-in fallbacks (which obviously are not working on platforms that provide optimized code...)
