### ISSUE TITLE
Adding Symbols to HTMLDOC

### ISSUE THREAD

**Issue by gkmundt** [michaelrsweet/htmldoc#422]
I have code for a registered trademark I'd like to appear on my PDF.  The HTML Doc has &reg;, but it is not appearing in the PDF.  Is there another method to add these symbols?

**Comment by michaelrsweet** [comment]
@gkmundt Can you provide a sample HTML file and command-line that reproduces the problem?

Also, what version of HTMLDOC are you using?

**Comment by gkmundt** [comment]
I am on using 1.8.28.  I renamed the .htm to .txt and uploaded.

Thank you,

[tmp_cttest.txt](https://github.com/michaelrsweet/htmldoc/files/6183040/tmp_cttest.txt)

**Comment by michaelrsweet** [comment]
@gkmundt OK, I've confirmed that &reg; shows up with the current HTMLDOC (1.9.11), so I suspect you are running into a known charset bug in older versions of HTMLDOC.

**Comment by gkmundt** [comment]
Okay, I will have to look at what I need to do to upgrade this.

Thank you,

Greg Mundt
e. ***@***.***
o. 616-493-8000
f. 616-454-7402
