### ISSUE TITLE
Internal links are broken in generated PDF

### ISSUE THREAD

**Issue by Dirk-Ho** [michaelrsweet/htmldoc#424]
In my Project I have pages with named anchors:

source.htm
... `<a href="target.htm#anchor">link</a>` ...

target.htm:
 ... `<a name="anchor">to here</a>` ...

If I generate a PDF, in version 1.9.11, all the resulting links are broken (clicking them yields an error message).
Generating exactly the same Project with version 1.9.3 will work.

**Comment by michaelrsweet** [comment]
@Dirk-Ho Can you provide a complete example HTML file along with the HTMLDOC command line you are using so I can try to reproduce this? The HTMLDOC Users Manual makes use of links like this extensively and I don't see this issue...

**Comment by michaelrsweet** [comment]
Closing due to lack of response. If you can supply the requested information I can re-open.
