### ISSUE TITLE
Linker Error while compiling the master repo

### ISSUE THREAD

**Issue by tany5522** [michaelrsweet/htmldoc#434]
Hi Michael,

I am trying to compile the htmldoc for Ubuntu and BBB.
In both the cases I ended up in a linker error.

_Linking htmldoc...
/usr/bin/ld: image.o: undefined reference to symbol 'png_get_image_height@@PNG12_0'
//lib/x86_64-linux-gnu/libpng12.so.0: error adding symbols: DSO missing from command line_

Please do help me to resolve this error.

**Comment by michaelrsweet** [comment]
@tany5522 I am not familiar with "BBB", but the error indicates that you don't have libpng16 which HTMLDOC depends on.

Check that you have the necessary dependencies installed, they have changed since the last HTMLDOC release (which had its own copy of libpng embedded...)
