### ISSUE TITLE
When installing HTMLDOC 1.19.12 getting configure: error: HTMLDOC requires zlib.

### ISSUE THREAD

**Issue by hpyjoy** [michaelrsweet/htmldoc#435]
I have been able to install HTMLDOC successfully with the following:

**htmldoc-1.9.11 && ./configure && make && make install**

when I try this:

**htmldoc-1.9.12 && ./configure && make && make install**

I get this error:

configure: error: HTMLDOC requires zlib.

I noticed in the release notes that this directory was removed.

**Comment by michaelrsweet** [comment]
@hpyjoy What operating system are you building on?

Did you read the instructions in "INSTALL.md"?
