### ISSUE TITLE
remove page numbering from PDF

### ISSUE THREAD

**Issue by beelzebubbles** [michaelrsweet/htmldoc#436]
Hi,
I checked the documentation and could not find an answer.

I am getting the page number printed on all PDF pages (bottom right). The command at its simplest:
`htmldoc --webpage -t  pdf -f  test.pdf test.html`
The html file has no footer, header or special HTML comments.

How can I completely disable printing the page number?

**Comment by michaelrsweet** [comment]
@beelzebubbles Add the "--header ... --footer ..." options to disable the default header/footer strings.

**Comment by beelzebubbles** [comment]
Thanks a lot for the prompt response,
to me it was not clear that --footer is 'enabled' and the default is "--footer ..1"
