### ISSUE TITLE
Convert HTML with Greek characters

### ISSUE THREAD

**Issue by papnikol** [michaelrsweet/htmldoc#443]
Hi,
I have noticed you mention some minimal support for Greek characters (which is what I need), but I do not seem to be ale to use it.

I am trying to convert a minimal HTML file but it does not seem to work, Greek characters come garbled.

I have posted a question [here](https://stackoverflow.com/questions/68565711/use-htmldoc-to-convert-html-that-contains-non-english-characters-greek-to-pdf), along  with what I have tried.

Any input from your part would be appreciated.

**Comment by michaelrsweet** [comment]
@papnikol You need to include the `--charset utf-8` option *before* the HTML file. Currently HTMLDOC doesn't read the charset from the HTML file...
