### ISSUE TITLE
Handling of utf-8 pages seems does not seem to work for special characters?

### ISSUE THREAD

**Issue by bm765** [michaelrsweet/htmldoc#445]
Hi,

thanks for maintaining this software! :-)

I used `/snap/bin/htmldoc https://www.msweet.org/htmldoc/ --webpage --outfile abc.pdf` to generate a pdf from an utf-8 based webpage (using `htmldoc 1.9.12` and Ubuntu 18.04).

Unfortunately, certain characters like `’` do not appear properly in the resulting pdf file (see attached). 

Website: 
`was developed in the 1990’s as a documentation`

PDF:
`was developed in the 1990â“s as a documentation`

Is there anything I can do about this by myself?

Thanks in advance.

[abc.pdf](https://github.com/michaelrsweet/htmldoc/files/6950889/abc.pdf)

**Comment by bm765** [comment]
Remark: I got the following messages during execution (but assume that they are not related to the issue):

```python3
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
ERR404: Not Found (https://www.msweet.org:443/htmldoc-160.png)
ERR007: Unknown image file format for "https://img.shields.io/github/sponsors/michaelrsweet?style=social".
ERR007: Unknown image file format for "https://img.shields.io/liberapay/patrons/michaelrsweet.svg?logo=liberapay".
PAGES: 2
BYTES: 241196                                                                  
```

**Comment by michaelrsweet** [comment]
Try adding “—charset utf-8” to the command…

**Comment by bm765** [comment]
I used the modified command as you suggested:
`/snap/bin/htmldoc https://www.msweet.org/htmldoc/ --charset utf-8 --webpage --outfile abc2.pdf` .

This leads to the following result in the pdf file:
`was developed in the 1990____s as a documentation` - just that the underscores are spaces only.

Copy pasting it here leads to: `was developed in the 1990âs as a documentation`

Please find attached the referring pdf file.

[abc2.pdf](https://github.com/michaelrsweet/htmldoc/files/7027110/abc2.pdf)

**Comment by michaelrsweet** [comment]
@bm765 You need to put the "--charset" option *before* the URL or file you are converting...

**Comment by bm765** [comment]
@michaelrsweet 
thanks for clarifying this. Now it works.

Maybe it might make sense to take even arguments after the URL / file into account... .
