### ISSUE TITLE
generates pdf without content

### ISSUE THREAD

**Issue by zsrainho** [michaelrsweet/htmldoc#457]
Hi.
When I try to generate a pdf with xxx lines (>466) it gives an error (internal) and creates a pdf with no content.
If you only try with 466 lines the pdf is generated.

I found the problem in the attribute `<tr bgcolor ="#F6F6F6"> ...</tr>`.
If you remove the attribute bgcolor from `<tr>...</tr> `it already works.

Here is the html that generates the pdf correctly (100 lines):
[bgcolor_error.zip](https://github.com/michaelrsweet/htmldoc/files/7726725/bgcolor_error.zip)

**Note:** add a few lines and it will break (>466)
I'm using version 1.9.7

_Command to execute:_
htmldoc -t pdf -f bgcolor_error.pdf --textfont helvetica --bodyfont helvetica --headfootsize 8 --fontsize 8 --webpage --size a4 --right 1cm --bottom 1cm --top 1cm --left 1cm --portrait bgcolor_error.html

**Comment by michaelrsweet** [comment]
@zsrainho I expanded this file to have 1000 table rows and was unable to reproduce this problem with the current version of HTMLDOC. Please try the current version and if you are still able to reproduce, attach the HTML file that reproduces along with any error messages that are shown.

**Comment by zsrainho** [comment]
Hi.
I updated to the latest version (1.9.13) and the error stopped happening, resolved. Thanks.

**Comment by michaelrsweet** [comment]
@zsrainho Great! Also, just released 1.9.14 with some security fixes so you probably want to update again…
