### ISSUE TITLE
Installer asks for a reboot on Windows 10

### ISSUE THREAD

**Issue by capr** [michaelrsweet/htmldoc#459]
1.9.13 msi installer says it cannot continue unless I reboot (says it has to modify some system files but doesn't say which). Bug?

**Comment by michaelrsweet** [comment]
@capr The Windows installer definitely shouldn't be requiring a reboot! I will investigate...

What version of Windows were you installing it on?

**Comment by capr** [comment]
Version	10.0.19042 Build 19042

**Comment by capr** [comment]
Btw, a "portable" exe would be nice. I suspect some people (like me) want to use this in scripts.

**Comment by michaelrsweet** [comment]
@capr Unfortunately, all of the supporting data files (fonts, etc.) and DLLs make this problematic to do for Windows...

**Comment by michaelrsweet** [comment]
@capr I just published a new 1.9.14 release, which has an updated installer (which I explicitly forced as "no reboot" - the previous setting was "reboot if needed" but that shouldn't be necessary for HTMLDOC...) Please let me know whether this resolves the problem for you.

**Comment by capr** [comment]
Yup, it's fixed.
