### ISSUE TITLE
No public PGP key available for v1.9.14 signatures

### ISSUE THREAD

**Issue by dbermond** [michaelrsweet/htmldoc#460]
The signature files for version 1.9.14 uses a different PGP public key from the previous releases. And this new key is not available on the default PGP keyserver, and also not on the Ubuntu keyserver. At least not for the `.tar.gz` signed source tarball, which is the one that I tested.

- htmldoc 1.9.14 PGP key ID: `BE67C75EC81F3244` (fingerprint: `9086C3CDC66C3F563CF8F405BE67C75EC81F3244`) (new key)
- htmldoc 1.9.13 PGP key ID: `999559A027815955` (fingerprint: `845464660B686AAB36540B6F999559A027815955`)

When trying to retrieve key ID `BE67C75EC81F3244` (new key) from the PGP keyserver:
```
$ gpg --recv-keys BE67C75EC81F3244
gpg: keyserver receive failed: No data
$ gpg --recv-keys --keyserver keyserver.ubuntu.com BE67C75EC81F3244
gpg: keyserver receive failed: No data
```

Previous key for 1.9.13 release (and earlier ones) can be received fine:

```
$ gpg --recv-keys 999559A027815955
gpg: key 999559A027815955: public key "Michael R Sweet <michael.r.sweet@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by michaelrsweet** [comment]
@dbermond It is true I'm using a new PGP key with the latest HTMLDOC release, and I *did* upload the key to keys.openpgp.org - I'll see if I can get it uploaded to Ubuntu's key server...

**Comment by michaelrsweet** [comment]
That is now done.

**Comment by dbermond** [comment]
Thank you!
