### ISSUE TITLE
Information on htmldoc - that supports on RHEL 8.0

### ISSUE THREAD

**Issue by senthilk99** [michaelrsweet/htmldoc#469]
Hi Michael,
We have htmldoc ver 1.8.28 installed on RHEL 6.9. Would like to know whether this can be installed on RHEL 8.0. We are in dire need of htmldoc that can be installed on RHEL 8.0.
In addition, how do we get the binary installs for installing it on RHEL 8.0. Request to share the link to the installable files as for some security reasons we cannot install snapstore on Linux server.

**Comment by michaelrsweet** [comment]
@senthilk99 It can absolutely be installed on RHEL 8.0, just follow the instructions for building on Linux.

**Comment by senthilk99** [comment]
Thank you so much. To get htmldoc 1.9.14 which is latest, other than snapstore, is there any other way we can download binaries for Redhat linux 8.0...

**Comment by michaelrsweet** [comment]
@senthilk99 Does your server support flatpak?

**Comment by michaelrsweet** [comment]
@senthilk99 If you have flatpak/flathub setup on your server you can install the current HTMLDOC test build (1.9.15) with:

    flatpak install --user https://dl.flathub.org/build-repo/75506/org.msweet.htmldoc.flatpakref

Hopefully it'll end up in the main hub/repository soon.

**Comment by michaelrsweet** [comment]
@senthilk99 HTMLDOC is now available via [Flathub](https://flathub.org/apps/details/org.msweet.htmldoc).
