### ISSUE TITLE
Option to control format of date-output

### ISSUE THREAD

**Issue by christophhalbi** [michaelrsweet/htmldoc#472]
Hi,

Is there any option to control the format of the date-output in header/footer?

**Comment by michaelrsweet** [comment]
No, HTMLDOC just uses the date format from the current locale. What are you trying to do?

**Comment by michaelrsweet** [comment]
Are you basing it on the server's locale, or do you want it to match the web browser language (Accept-Language header)?

**Comment by christophhalbi** [comment]
On the server's locale

**Comment by michaelrsweet** [comment]
OK, well it should be picking it up already. What are the values of the LANG and LC_xxx environment variables?

**Comment by michaelrsweet** [comment]
OK, take a deeper look into this - it should be picking up the locale for the date/time format. What OS/Linux distribution are you using?

**Comment by christophhalbi** [comment]
Thank you

NAME="openSUSE Leap"
VERSION="15.3"

**Comment by christophhalbi** [comment]
htmldoc --version
1.9.12

**Comment by michaelrsweet** [comment]
Try:

```
LC_TIME="de_DE.UTF-8" htmldoc ...
```

**Comment by christophhalbi** [comment]
Hi,

No, doesn't work.

**Comment by christophhalbi** [comment]
What's interesting: without LC_ALL or LC_TIME I get something like 03/22/2022 05:56:29 AM. When I use LC_ALL I get 22.03.2022 05:57:32.
So it actually does something.

**Comment by michaelrsweet** [comment]
Right, I'm not sure if there is a way to customize the date format for a particular locale (I think you need to edit the glibc sources), so right now the best you can do is find a locale that formats the date and time the way you like and set `LC_TIME` accordingly.

**Comment by michaelrsweet** [comment]
OK, I've updated HTMLDOC to support date/time format strings so you can customize things:

[master a67e9cc] Add support for "$DATE(format)" and "$TIME(format)" header/footer strings (Issue #472)

This will be part of the upcoming HTMLDOC 1.9.16 release.

**Comment by christophhalbi** [comment]
Thank you very much!
