### ISSUE TITLE
Support for <table style="float:left;"> 

### ISSUE THREAD

**Issue by ipod86** [michaelrsweet/htmldoc#474]
Hello, 
is it possible to add support for something like this?

```
<table style="float:left;">
  <tr>
    <td>Tabelle 1</td>
  </tr>
</table>
<table style="float:left;">
  <tr>
    <td>Tabelle 2</td>
  </tr>
</table>
```

**Comment by michaelrsweet** [comment]
@ipod86 Unfortunately, HTMLDOC does not support arbitrary CSS as it was developed many years ago for HTML 3.2... If I do ever get [HTMLCSS](https://github.com/michaelrsweet/htmlcss) finished up, a new version of HTMLDOC based on that HTML/CSS engine will support floating tables. Sorry...
