### ISSUE TITLE
Set paper size

### ISSUE THREAD

**Issue by BartVanderDonck** [michaelrsweet/htmldoc#492]
Hello,

When we print a PDF-file that was generated by htmldoc, the print window displays 8.5 x 11 inch by default. That is the standard paper format in the USA. But in Europe, we are using the A4 letter format .

Is there a way in htmldoc to set the print window to A4 by default ? Now we need to change it every time by hand.
![unnamed](https://user-images.githubusercontent.com/54753703/176608502-4098c569-bd72-4c3b-9ea7-745e7417e1c5.png)

Thank you, Bart

**Comment by michaelrsweet** [comment]
@BartVanderDonck Note that HTMLDOC has *zero* control over the print experience on a given platform. Without knowing the PDF file you are trying to print, it is impossible to provide any guidance, but *normally* the print dialog will show either the locale default size or the ready (loaded) media size closest to the PDF dimensions.

The default output size for HTMLDOC is a so-called "universal" size (8.27x11in - A4 width and US Letter height) that can print without scaling on either A4 or Letter. You can force A4 size with the `--size a4` option or corresponding comment string.
