### ISSUE TITLE
Problems with running configure on SLES12SP5 / zlib

### ISSUE THREAD

**Issue by FujiChrissi** [michaelrsweet/htmldoc#493]
Hello,

I try to compile HTMLDOC on a SLES12SP5 system. I checked the description about the dependencies and installed all required and optinal packages.

When I run ./configure I got the error 

```
checking for library containing gzgets... no
configure: error: HTMLDOC requires zlib
```

zlib (zlib-devel-1.2.11-11.19.1.x86_64) is installed.

When I try the same on a SLES15SP3 system it is working (zlib-devel-1.2.11-150000.3.30.1.x86_64). 

On the SLES12SP5 system I have
- gcc version 4.8.5 (SUSE Linux)
- GNU Make 4.0

I checked the project on GitHub for open and closed issues but could not find anything. 

What can I do to check this further?

Best regards

--Christian

**Comment by michaelrsweet** [comment]
Can you provide a copy of your config.log file? Something is failing for the configure test...

**Comment by FujiChrissi** [comment]
[config.log](https://github.com/michaelrsweet/htmldoc/files/9188326/config.log)

Thank you for your investigation.

**Comment by michaelrsweet** [comment]
@FujiChrissi OK, it looks like your local installation of FLTK is messed up and causing the problem. If you don't need the GUI, just add the "--without-gui" configure option to eliminate FLTK from the equation. If you do, please verify that your installation of FLTK is correct...

**Comment by FujiChrissi** [comment]
@michaelrsweet  Thank you very much for your analysis and information. I will update the system with the latest patches for this OS. If the error is still there I will use it without the gui. We do not need it.

**Comment by FujiChrissi** [comment]
Patching SLES12SP5 with the latest patches did not solve the configure issue.
Running ./configure --without-gui was now without the ZLIB error.

When I run make I got the following error

```
# make
Making all in htmldoc...
Compiling gui.cxx...
make[1]: g++: Command not found
../Makedefs:91: recipe for target 'gui.o' failed
make[1]: *** [gui.o] Error 127
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 1
```

This makes me wonder as I had run configure with the option without the gui.

[config.log](https://github.com/michaelrsweet/htmldoc/files/9220267/config.log)

**Comment by michaelrsweet** [comment]
@FujiChrissi The config.log file doesn't show you passing "--without-gui"...

**Comment by FujiChrissi** [comment]
Here is the output from the shell when I run configure --without-gui
[configure_without-gui.txt](https://github.com/michaelrsweet/htmldoc/files/9220544/configure_without-gui.txt)
i

**Comment by michaelrsweet** [comment]
@FujiChrissi Hmm, you also don't have the JPEG or PNG libraries installed. What does the Makedefs file contain?

**Comment by FujiChrissi** [comment]
Here is the outout from the Makedefs file.
[Makedefs.txt](https://github.com/michaelrsweet/htmldoc/files/9220689/Makedefs.txt)

**Comment by FujiChrissi** [comment]
Here is the output from the installed jpeg and png libraries

```
shcprod:~/chrissi/HTMLDOC/htmldoc-1.9.16 # rpm -qa | grep jpeg
libjpeg8-8.1.2-31.25.1.x86_64
libjpeg8-32bit-8.1.2-31.25.1.x86_64
libmjpegutils-2_0-0-2.0.0-13.226.x86_64
shcprod:~/chrissi/HTMLDOC/htmldoc-1.9.16 # rpm -qa | grep png
latex2html-pngicons-2012-1.347.noarch
libpng16-16-32bit-1.6.8-15.5.2.x86_64
libpng16-16-1.6.8-15.5.2.x86_64
```

**Comment by michaelrsweet** [comment]
@FujiChrissi You need the libjpeg8-devel and libpng16-devel packages.

I don't see anything obviously wrong here, but since the error you are getting is that the C++ compiler can't be found I would look to see whether you have it installed...

**Comment by FujiChrissi** [comment]
gcc is installed.

```
shcprod:~/chrissi/HTMLDOC/htmldoc-1.9.16 # gcc --version
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

shcprod:~/chrissi/HTMLDOC/htmldoc-1.9.16 # which gcc
/usr/bin/gcc
```

**Comment by michaelrsweet** [comment]
@FujiChrissi You also need g++ (the C++ frontend) - gcc is just the C front-end.

**Comment by FujiChrissi** [comment]
@michaelrsweet 
Ok. 
I understand this now a bit better. I was able to install some missing things in SLES12SP5
```
- g++
- jpeglib.h
- png.h

```
I am now able to run configure, make and make install without errors. 
Many many thanks for your support and creating this tool.
