### ISSUE TITLE
Fonts character set needs an app restart to be applied in case of a second (and more file generation)

### ISSUE THREAD

**Issue by Faign** [michaelrsweet/htmldoc#496]
The font character (tested only with utf-8) set is applied only once (for one html to pdf file generation). So the app has to be restarted for it to be taken into account for other new files generation.

**Comment by michaelrsweet** [comment]
Are you referring to converting multiple documents via the GUI? If so, yeah that'd be a bug - each conversion should be a clean run.

**Comment by michaelrsweet** [comment]
[master a4b0dfe] Fix multiple conversions from the GUI (Issue #496)

**Comment by Faign** [comment]
> Are you referring to converting multiple documents via the GUI? If so, yeah that'd be a bug - each conversion should be a clean run.

Yes, that's what I meant. (Sorry for the late answer).
