### ISSUE TITLE
Accented characters cause display issues in v1.9 this was OK in v1.8

### ISSUE THREAD

**Issue by Sparky10** [michaelrsweet/htmldoc#497]
When converting content that contains accented characters we find that we run into a number of display issues.  This has started happening in v1.9 and was not an issue in v1.8.

**Original HTML**

<!DOCTYPE html>
<html>
<body>
 <table border="1">
    <tr>
        <td>col1</td>
        <td>col2</td>
        <td>&#x015f;arap and &#x015f;ama&#x015f;<td>
        <td>0.00</td>
        <td>3</td>
    </tr>
</table>
</html>

**V1.8 conversion**
![image](https://user-images.githubusercontent.com/5199232/202751142-98755957-9a50-47c1-9b0b-4395475bf103.png)

**V1.9 conversion**
![image](https://user-images.githubusercontent.com/5199232/202750903-e1d45b9b-7604-44ee-8e34-4d3fa0dc3f3a.png)

**Comment by michaelrsweet** [comment]
@Sparky10 What options are you passing on the command-line?

**Comment by michaelrsweet** [comment]
FWIW, when I use the default (ISO-8859-1) character set I see this problem but if I specify UTF-8 the right thing comes out:

```
htmldoc --webpage --charset utf-8 -f FILENAME.pdf FILENAME.html
```

**Comment by Sparky10** [comment]
Thanks Michael, we will check this out and I will update here with results.
