### ISSUE TITLE
IMages not showing.. 

### ISSUE THREAD

**Issue by wmdhosting** [michaelrsweet/htmldoc#499]
We use 1.9.11 on server and all works OK.   with one site..

Now we moved another site to that server ..  that  worked well on other server with version 1.8.28
but now on 1.9.11 images not showing.. .. 
just bg footer image showing. as that is command line settings

We tryed all images formats. and all same settings  from site where all work OK..

But  still images do not show.. 
any idea. or how to debug that..
Thx

**Comment by michaelrsweet** [comment]
Well, what format for the images? Are they local files or remote?

How are you running HTMLDOC on your server?

**Comment by wmdhosting** [comment]
i tryed all formats.    they are local.. 

1. first site all images showing ok..  ( 1.9.11) 
2.  second site. allmost same script  ( worked well on 1.828 .. but not showing images on 1.9.11 

How are you running HTMLDOC on your server?
Dont know what you mean.. here..
