### ISSUE TITLE
snap install - missinf fonts and data directory

### ISSUE THREAD

**Issue by jiri-hadamek** [michaelrsweet/htmldoc#502]
We have installed htmldoc from snap

>snap list
htmldoc            1.9.16           747    latest/stable  michaelrsweet  -

but in squashfs are missing fonts (all files) and data directory

[root@work]# ls /snap/htmldoc/747/usr/share/**fonts**/
truetype

[root@work]# ls /snap/htmldoc/747/usr/share/**data**/
ls: cannot access '/snap/htmldoc/747/usr/share/data/': No such file or directory

**Comment by michaelrsweet** [comment]
Look in `/snap/htmldoc/NNN/usr/share/htmldoc/fonts` - that's where the fonts are stored, not /usr/share/fonts.
