### ISSUE TITLE
Footer behavior from older version

### ISSUE THREAD

**Issue by ldesrosiers** [michaelrsweet/htmldoc#504]
We are moving from Unix to Windows and upgrading to newer version of HTMLDOC.

Currently we have 1.8.27 in Unix and are moving to 1.9.12 with Windows.

In version 1.8.27, when we have an image in the Center Footer, the image would display actual size.

With 1.9.12, this same image in Footer is showing very small.

I believe this was a bug fix somewhere to fix the Header/Footer scaling.  

Is there anyway to get the footer to behave as it did in 1.8.27?

Thank you.

**Comment by michaelrsweet** [comment]
Sorry, this was an intentional bug fix in *v1.8.30*, which was released a very long time ago.

However, issue #372 introduced a new "letterhead" image format (big 'L' in the `--header`/`--footer` option value or `$LETTERHEAD` in header/footer comments in the HTML) that probably does what you want.
