### ISSUE TITLE
<pre> tag indent

### ISSUE THREAD

**Issue by mamcgree** [michaelrsweet/htmldoc#505]
I have many legacy html documents that were using the `<pre>` tag for alignment.  Upgraded to the latest HTMLDOC, and the `<pre>` tag indents.  Is there a switch to turn off the indent, or a workaround.

Thankyou

Cheers..

**Comment by michaelrsweet** [comment]
Looks like I made this change about 6 years ago (d8d3ce169c2bdc33072e11e1afcb308fcd9d26cb) along with some other monospace rendering changes. Will look at ways to support indented vs. non-indented.

**Comment by mamcgree** [comment]
thank you so much.. yes it is from years ago, and finally updating systems,  and it broke all our creations..  even if you put a command line option --no-indent  or something we would be eternally greatful.

cheers
Mark..

May 30, 2023 11:55:48 a.m. Michael R Sweet ***@***.***>:

**Comment by michaelrsweet** [comment]
[master af6e9eb] Add --pre-indent option and corresponding GUI support (Issue #505)
