### ISSUE TITLE
Default value of print scale

### ISSUE THREAD

**Issue by BartVanderDonck** [michaelrsweet/htmldoc#506]
Hello,

When we print a PDF file that was generated by HTMLDOC, the default print settings for "Scale" depend on the browser. For example, my Chrome uses "100%" as default, and my MS Edge uses "Shrink To Printable Area" as default.

Is there any way we can set this default value from HTMLDOC ? Other print settings can be set like page size (eg. A4), portrait/landscape mode, etc.

![parametres imprimer](https://github.com/michaelrsweet/htmldoc/assets/54753703/25a0cc9b-8a77-4488-afa5-51d770688c1d)

Thank you, Bart

**Comment by michaelrsweet** [comment]
Sorry, there isn't a way to control this in the PDF output - the size is something that is part of the PDF format but not the print options...
