### ISSUE TITLE
1.9.17 libcups is required but not mentioned in docs except release note

### ISSUE THREAD

**Issue by BrianInglis** [michaelrsweet/htmldoc#513]
Would be nice to know where to get a compatible version of libcups, as it does not appear to be in your repos, and does not appear to be mentioned in the docs except release notes and configs. 
Under OpenPrinting there appears to be a beta 3.0 of such a library - is this adequate for this release of HTMLDOC? 
Upgrading Cygwin release, which does not support CUPS, probably because some requirements can not be satisfied, as the port attempt appears to have been abandoned over a decade ago.

**Comment by michaelrsweet** [comment]
You want the current stable CUPS libraries as part of [CUPS 2.x](https://openprinting.github.io/cups). The Windows Visual Studio project uses the NuGet packages, and you shouldn't have any trouble compiling from source as needed...

**Comment by BrianInglis** [comment]
Compiling with Cygwin x86_64-pc-cygwin host gcc, does not support CUPS or mono, so .NET and Windows are non-starters!

**Comment by michaelrsweet** [comment]
Cygwin *should* be able to run the configure script included with the CUPS sources. Beyond that I can't really help as I only build HTMLDOC on Windows with Visual Studio...
