### ISSUE TITLE
Problem with emphasis when converting directly from markdown to pdf

### ISSUE THREAD

**Issue by PeterHero** [michaelrsweet/htmldoc#517]
First of all I'd like to thank you for your time and effort you have put in the tool. It stands out among the many, because it is not bloated as some other, but simply converts html or md to pdf.

I encountered incorrect formatting of **emphasized** or _italic_ text when converting md file to pdf: 
`htmldoc --webpage -f foo.pdf foo.md`

When used with html in the middle it works as expected:
`htmldoc --webpage foo.md | htmldoc --webpage -f foo.pdf -`

**Comment by michaelrsweet** [comment]
Can you attach a sample markdown file that shows this? Also, what version of HTMLDOC are you using?

**Comment by PeterHero** [comment]
foo.md:
```
test *test* **test**
```
version:
```
$ htmldoc --version
1.9.17
```

**Comment by michaelrsweet** [comment]
[master eb3e99f] Fix markdown text styles (Issue #517)
