### ISSUE TITLE
Broken zlib detection on OpenSUSE

### ISSUE THREAD

**Issue by stefan6419846** [michaelrsweet/htmldoc#519]
I tried to build the package on OpenSUSE 15.4, but for some reasons I got told:

> checking for library containing gzgets... no
> configure: error: HTMLDOC requires zlib.

After changing the offending line of `configure.ac` from https://github.com/michaelrsweet/htmldoc/blob/055acba8778702eb06ba3de8dd208efabccde92a/configure.ac#L236 to

```
AS_IF([$PKGCONFIG --exists zlib], [
```

and regenerating the `configure` script, everything worked fine afterwards.

**Comment by michaelrsweet** [comment]
Not every OS uses pkg-config, so we need to use the AC_SEARCH_LIBS if there is no zlib package file.

**Comment by michaelrsweet** [comment]
[master 6d7d843] Use pkg-config for initial zlib check (Issue #519)
