### ISSUE TITLE
Is it possible to support codepage 437? (e.g. PC graphics)

### ISSUE THREAD

**Issue by erco77** [michaelrsweet/htmldoc#522]
I maintain an MS-DOS based project whose manual occasionally uses PC graphics characters (cp-437) for things like tables, equipment wiring diagrams, schematics, and the like in lieu of images. The use is limited to the line/box drawing characters in the range 0xB0..0xDF.

I'm able to generate the 300 page manual just fine with scripts that convert the ASCII to html, but having trouble with the PC graphics in the htmldoc generated PDF.

I noticed htmldoc comes with several code page files, but not cp-437. Was wondering if I can make one myself by copying e.g. cp-1250, and then revising the byte code mappings for 0xB0 thru 0xDF as per the unicode equivalent 4 digit byte codes shown in this table ([source](https://int10h.org/oldschool-pc-fonts/readme/)):
![image](https://github.com/michaelrsweet/htmldoc/assets/6484779/c21370f8-f329-4dc9-82f1-dfba873d92af)

So for instance, in the new cp-437 file:
```
[..cp-1250 content up to this point..]
B0 2591
B1 2592
B2 2493
B3 2502
B4 2524
[..similar mods thru DF, then back to the cp-1250 values past that..]
```
I'm hoping if that's right, then I can then use `"---charset cp-437"` to possibly get satisfactory results with a fixed width font like Courier.

Is that a good way to go about this? Or is there perhaps another way?
I don't know much about the cp-xxxx files yet, I'm just guessing at what they do, and hoping the fonts I'm mapping to would actually include those box drawing characters as part of their unicode support.

**Comment by michaelrsweet** [comment]
That is the way to do it. I don't think the included fonts contain these glyphs but that's how you would add the character set.

**Comment by erco77** [comment]
Thanks mike, good to know I'm at least going in the right direction.

It seems it _might_ be possible to convert a ttf font from [here](https://int10h.org/oldschool-pc-fonts/)  which contains all the glyphs for all ASCII + PC graphics chars, and convert it to the afm/pfa files that htmldoc uses.

**Comment by erco77** [comment]
Revisiting this closed issue with a solution that seemed to work for me, after a year or so of no luck. Didn't seem to involve any changes to htmldoc.

In short: using a perl script to convert my raw DOS text files containing IBM PC box drawing chars (cp-437) into html, using utf-8 equivalents for all the box/block/shade characters, then used this htmldoc command to convert the html files to pdf:
```
htmldoc --book \
         --charset utf-8 \
         --bodyfont monospace \
         --embedfonts \
         --fontsize 10 \
         --headingfont courier \
         --headfootfont courier \
         --headfootsize 14 \
         --top .20in \
         --bottom .20in \
         -t pdf -f $outputpdf \
         $htmlfiles
```
The key bit being the `--charset/--bodyfont/--embedfonts` flags.

Apparently the `monospace` font on my ubuntu 24.x machine  includes the right glyphs for this, whereas the courier font _did not_, which was I think what was causing me the most issues getting garbage text for the box drawing diagrams.

With courier I was getting:

<img width="822" height="645" alt="Image" src="https://github.com/user-attachments/assets/3351abd5-af9c-4434-9db2-ba9ff27abd73" />

..and with "--bodyfont monospace" I'm now getting the correct result:

<img width="815" height="696" alt="Image" src="https://github.com/user-attachments/assets/9c84f0b4-716e-4fc5-970a-ed1998120736" />

There were quite a few warnings while htmldoc ran, saying:
```
ERR011: Too many Unicode code points.
```
..not sure what that was about, but it seemed to work anyway.

**Comment by michaelrsweet** [comment]
@erco77 The "Too many Unicode code points." error just means that you used more than 128 Unicode characters. In UTF-8 mode HTMLDOC creates a custom 8-bit encoding from the document data, with base ASCII characters + 128 dynamically-allocated "extended" characters. This works fairly well for plain text but you might run out when you use a lot of discrete graphic/symbol characters.

**Comment by erco77** [comment]
Ya, I wasn't sure thought what was triggering that; I only use about 32 of the block characters, so not sure what might be using the other (128-32) that would cause it to run out of code points.

Maybe I can modify the error message to show either the text or character byte sequence in question that's generating those errors in order to pin it down.

**Comment by erco77** [comment]
Suggesting this patch to `htmldoc` which helped me identify which of my documents was using up all the code points:

```diff
diff --git a/htmldoc/htmllib.cxx b/htmldoc/htmllib.cxx
index 5938152..860c0ed 100644
--- a/htmldoc/htmllib.cxx
+++ b/htmldoc/htmllib.cxx
@@ -1859,7 +1859,7 @@ htmlMapUnicode(int ch)            // I - Unicode character
 
   if (_htmlUTF8 >= 0x100)
   {
-    progress_error(HD_ERROR_READ_ERROR, "Too many Unicode code points.");
+    progress_error(HD_ERROR_READ_ERROR, "Too many Unicode code points. (%08x)", (unsigned int)ch);
     return (0);
   }
```
The list of errors I got were:
```
ERR011: Too many Unicode code points. (00000398)
ERR011: Too many Unicode code points. (000003a9)
ERR011: Too many Unicode code points. (000003b4)
ERR011: Too many Unicode code points. (0000221e)
ERR011: Too many Unicode code points. (000003c6)
ERR011: Too many Unicode code points. (000003b5)
ERR011: Too many Unicode code points. (00002229)
ERR011: Too many Unicode code points. (00002261)
ERR011: Too many Unicode code points. (000000b1)
ERR011: Too many Unicode code points. (00002265)
ERR011: Too many Unicode code points. (00002264)
ERR011: Too many Unicode code points. (00002320)
ERR011: Too many Unicode code points. (00002321)
ERR011: Too many Unicode code points. (000000f7)
ERR011: Too many Unicode code points. (00002248)
ERR011: Too many Unicode code points. (000000b0)
ERR011: Too many Unicode code points. (00002219)
ERR011: Too many Unicode code points. (000000b7)
ERR011: Too many Unicode code points. (0000221a)
ERR011: Too many Unicode code points. (0000207f)
ERR011: Too many Unicode code points. (000000b2)
ERR011: Too many Unicode code points. (000025a0)
ERR011: Too many Unicode code points. (00002302)
ERR011: Too many Unicode code points. (000000a0)
```
With the help of google to look those up, they seem to all be greek and math symbols.

I found that in google I could just search for `unicode point lookup 2320`, where I take the last 4 digits from the above error messages, telling me the actual Unicode character name and character:

**Unicode point U+2320 is the Top Half Integral (⌠)**

With that I was able to grep my docs for that character, and found the problem; one document includes a _full ASCII "wall chart"_ that includes all chars above 0x7f! I trimmed off that part of the document, and now htmldoc runs without errors.
