### ISSUE TITLE
v1.9.18 Mac version crashes immediately on startup

### ISSUE THREAD

**Issue by SoftwareEngineeringLLC** [michaelrsweet/htmldoc#524]
Sorry to have to report this, but immediately on startup on my MacBookPro M1P running macOS 14.4.1, this happens...

[htmldoc_v1-9-18_crashreport.txt](https://github.com/michaelrsweet/htmldoc/files/15284255/htmldoc_v1-9-18_crashreport.txt)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               htmldoc [4261]
Path:                  /Applications/htmldoc.app/Contents/MacOS/htmldoc
Identifier:            org.msweet.htmldoc
Version:               1.9.18 (1.9.18)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-05-11 13:37:01.9567 -0700
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        AA807141-C650-5AAB-3927-13B0460FF1E9

Time Awake Since Boot: 170000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x3f80000000000011 -> 0xffff800000000011 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x3f80000000000011

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4261]

**Comment by michaelrsweet** [comment]
Thanks, I'm guessing this is an Apple regression (I was able to reproduce on my M1 Max system but not my Intel system) but I'll dig deeper to figure out what is going wrong.

**Comment by rsozdance** [comment]
I am facing the same issue, any new updates?

**Comment by michaelrsweet** [comment]
OK, just releasing a new version and new binaries, please re-test.
