### ISSUE TITLE
Links for files in subfolders fail

### ISSUE THREAD

**Issue by prichterich** [michaelrsweet/htmldoc#525]
Up to htmldoc version 1.9.3, htmldoc handled links to files in subfolders correctly. Later versions, including 1.9.18, create non-functional links in the PDF file. For example, this link:
`<a href="edit/edit_undo.htm">Undo</a>`
in the PFD file does not work, and hovering shows a file link instead of the usual "Go to page #":
`file://Users/Shared/.../edit/edit_undo.htm`
The corresponding object entry in the PDF file is:
`obj<</S/Launch/F(edit/edit_undo.htm)>>endobj`

A ZIP archive with an example that works in 1.9.3 but fails in 1.9.18 is attached.
[htmldoc_link_bug2.zip](https://github.com/michaelrsweet/htmldoc/files/15336670/htmldoc_link_bug2.zip)

**Comment by michaelrsweet** [comment]
Will investigate for 1.9.19...

**Comment by michaelrsweet** [comment]
Reproduced, investigating...

**Comment by michaelrsweet** [comment]
[master 274189f] Fix links to subfolders (Issue #525)
