### ISSUE TITLE
utf-8 encoding problem.

### ISSUE THREAD

**Issue by anotatta** [michaelrsweet/htmldoc#526]
Thanks for promising software.

I ran into utf-8 encoding problem on the output file.  The command used is
`htmldoc.exe --charset utf-8 --outfile out.html index.html`

where index.html is:
`<html>`
`<head><meta charset="UTF-8"></head>`
`<body><p>`
`abcdef...z<br>`
`āīūṭḍḷṁṇṅṃĀ`
`</p></body></html>`

The output shows wrong character
`abcdef...z
�����������`

Thanks for any help or pointer.

**Comment by michaelrsweet** [comment]
What version of HTMLDOC?

What OS/Linux distribution?

Did you install a package or compile from source?

**Comment by anotatta** [comment]
htmldoc binary version 1.9.18. for Window 10 from  htmldoc-1.9.18-windows.msi

**Comment by michaelrsweet** [comment]
[master 4c61bca] Fix export of HTML when using UTF-8 (Issue #526)
