### ISSUE TITLE
Links should be case sensitive

### ISSUE THREAD

**Issue by mdykierek** [michaelrsweet/htmldoc#530]
Anchors in HTML are case sensitive, ie ANCHOR1 and anchor1 are not the same targets.
It seems that htmldoc converts all to lower case.
When making links to case sensitive descriptions, the links should go to appropriate anchors.
If I wanted to link -a and -A in description of the "ls" command and use "a" and "A" as anchors, I cannot.

**Comment by michaelrsweet** [comment]
HTMLDOC was originally written for HTML 2/3, before "id" became a thing and URL targets were "maybe" case-insensitive, so I just treated them as case-insensitive.  This is the first time in 30 years that anyone has noticed/cared...

**Comment by mdykierek** [comment]
An automated system that translates kind of markup to documentation including actual syntax for commands generates <a name=...> with both upper and lower case. Then, the links jump only to the lower case command's option description.
If it were manual, I would probably care less.

**Comment by michaelrsweet** [comment]
[master 924b66b] Make link targets case sensitive (Issue #530)
