### ISSUE TITLE
HTMLDOC fails with error "entry point BCryptHash could not be located" - Windows 2012 related?

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [michaelrsweet/htmldoc#531]
We had a working HTMLDOC 1.9.16 and upgraded to HTMLDOC 1.9.18, cause this would fix some trouble we had with high amounts of tables in the processed html. 
In the test environment the newer HTMLDOC version fixes this problems and generates pdfs the older version could not.

In the prod environment HTMLDOC 1.9.18 will show this error:
![image](https://github.com/user-attachments/assets/83041bc4-fe40-4a21-99b3-c5cd6c1bc7f7)
The procedure entry point BCryptHash could not be located in the dynamic link library c:\htmldoc\libcups2.dll.

Its noteworthy that the prod system is running with windows 2012, while the test systems were win10 - this might very well be the culprit.
If it is intended to not support that old system, please ignore/close this issue.

**Comment by michaelrsweet** [comment]
Yeah, the newest libcups code is Windows 10+ or Windows Server 2016+.
