### ISSUE TITLE
Version 1.9.19 drops spaces between words

### ISSUE THREAD

**Issue by prichterich** [michaelrsweet/htmldoc#533]
htmdoc version 1.9.19 drops spaces between words in generated PDF files. This seems to be a new bug, possible buffer and/or keyword related. A simple example is attached.
[htmldoc_spaces_bug.zip](https://github.com/user-attachments/files/17925608/htmldoc_spaces_bug.zip)

**Comment by michaelrsweet** [comment]
It doesn't look like there is a buffer/keyword issue - HTML output preserves the spacing so there is something happening when the PDF/PS output is formatted.

Was the last version you used 1.9.3? I haven't had any reports of this issue before so I need to figure out when this broke...

**Comment by totalAldo** [comment]
This is also happening to me and the last version I used was 1.9.18

**Comment by michaelrsweet** [comment]
@totalAldo Great, thank you that helps a lot!

**Comment by michaelrsweet** [comment]
This might be a regression caused by the fix for #528. Investigating...

**Comment by prichterich** [comment]
Version 1.9.3 is the last version that I can use for our application. Versions after that one have bugs that make the PDF files generated useless. One of these problems was the broken links to external files, which I previously reported. That seems to be fixed in this release, but the missing spaces issue again prevents upgrading.

**Comment by prichterich** [comment]
The reason I suggested it might be a buffer and/or keyword issue is that I only observed the problem when files are large enough (> 1 kb), and the drops seemed more common before words like "as" and "for". Adding content (plain text paragraphs) at the beginning of a file can change where or if the problem occurs. But it's just a guess, and spaces are removed before other words, too.

**Comment by michaelrsweet** [comment]
OK, I reverted that one change and it didn't make a difference.

**Comment by prichterich** [comment]
If you want me to check changes before a release, I'd be happy to. I use htmldoc to generate a help file with about 400 pages from many dozens of source files, organized in multiple folders. We also generally check the PDF carefully for problems.

**Comment by michaelrsweet** [comment]
@prichterich I've found the cause - the code to drop the leading space in some situations was modifying the string in place, which wasn't a problem until I added the string pool for 1.9.19, so duplicate strings started using the same pointer and storage...

Try the latest code on Github:

[master 38f89c2] Fix regression causing missing whitespace (Issue #533)

**Comment by prichterich** [comment]
I usually download and use the app. I tried downloading and building the code, but no luck. Tried XCode first, which I have not used for more than a decade, and got past the first 2 hurdles (signing and full disk access), but the get stuck on dependencies not being installed (I assume - FL/Fl.H file not found). No luck from the command line, either, where I get the error "error: pkg-config is required for library checks" when running configure. I'd probably run into dependency problems next, anyway.

I'm afraid I'd need rather detailed build instructions after getting spoiled by homebrew etc. for years. Tried brew install htmdoc, too, but that installs version 1.9.19.

**Comment by prichterich** [comment]
The spaces issue is fixed, but unfortunately, not all file links work. There seem to be some patterns, though. Many links that are broken (show up as file links) are to a file in a sub-directory, like this:
`<a href="edit/edit_undo.htm">Undo</a>`
If there is a named link after the file name, then the link works. Example:
`<a href="edit/edit_copy.htm#paste">Paste</a>`

Also, links at the end of an HTML paragraph seem to break. Example:
```
<blockquote>
<p><a href="about.htm">About ..</a><br>
<a href="preferences.htm">Preferences...</a><br>
<a href="exit_application.htm">Quit</a></p>
</blockquote>
```
The first two links work, the third one does not (shows up as a "file" link). However, there are also examples where the last link that looks very similar to the above works fine.

**Comment by michaelrsweet** [comment]
@prichterich If you aren't getting an error/warning about the missing link, please file a new bug for that so I can fix it.
