### ISSUE TITLE
Broken links to files in subfolders.

### ISSUE THREAD

**Issue by prichterich** [michaelrsweet/htmldoc#534]
Links to files in subfolders are broken in version 1.9.19, and are still broken in the current code for 1.9.20. In the 1.9.20 code, links to files in subfolder work only if the link also includes a named anchor (e.g. target.htm#myanchor). If the link is does not include the #anchor, then it shows up as the "file" link in the generate PDF file. Here's a demo project:
[htmldoc_link_bug3.zip](https://github.com/user-attachments/files/17952390/htmldoc_link_bug3.zip)

**Comment by michaelrsweet** [comment]
I think I have it fixed properly now (and also the target page/position):

[master f6fb9e4] Update the file link code to add both the basename and relative filename within the document tree, and to put the target at the top of the page that actually contains the start of the HTML file (Issue #534)

**Comment by prichterich** [comment]
Works well now. Thanks for the fix. Glad to be able to update to the newest version.

**Comment by michaelrsweet** [comment]
Thanks for the update, I'll push out a new official release soon.

**Comment by prichterich** [comment]
Here's a tip for anyone who needs to check for broken links in a self-contained PDF file that's created from a large collection of HTML files. Sometimes, links do not work because of typos in file names, moving files around, etc. Manual checking of all links in such a file is tedious and error-prone. But such broken links can easily be found as follows:
- open the PDF file in a text editor (I use BBedit on macOS, but any editor should work)
- search for "S/Launch/F" - these are links to external files; example:
`1577 0 obj<</S/Launch/F(using_help.htm)>>endobj`
- to find out where the wrong link is used, use "Search in multiple files" to search for it (for "using_help.htm") in the example

**Comment by prichterich** [comment]
You may want to hold off the release, there may be one more issue to fix. Looking at all the broken links in our documentation, there is a large number that look like this:
`1171 0 obj<</S/Launch/F(../feature_prefs.htm)>>endobj`
I suspect that relative links to a parent folder may not work. I've checked only one link so far, but that one seems to be fine in the html file. Of the 26 different broken links in the PDF file, 16 are to a file in a parent folder. The others I looked at so far are typos, renamed files where the links were not update, files that were missing in the book file, and so on.

**Comment by prichterich** [comment]
Indeed, linking to a file in a parent folder using a relative link does not work, unless the link is to a named anchor. A test project is attached.
[htmldoc_link_bug4.zip](https://github.com/user-attachments/files/17963323/htmldoc_link_bug4.zip)
